insert into hvs.product (id, name, wanted_amount) values (1, 'Pail With Metal Handle 16l White', 78);
insert into hvs.product (id, name, wanted_amount) values (2, 'Scallops - 20/30', 43);
insert into hvs.product (id, name, wanted_amount) values (3, 'Wine - Cabernet Sauvignon', 88);
insert into hvs.product (id, name, wanted_amount) values (4, 'Cheese - Havarti, Roasted Garlic', 5);
insert into hvs.product (id, name, wanted_amount) values (5, 'Oxtail - Cut', 86);
insert into hvs.product (id, name, wanted_amount) values (6, 'Beef - Rib Roast, Capless', 94);
insert into hvs.product (id, name, wanted_amount) values (7, 'Table Cloth 53x69 White', 71);
insert into hvs.product (id, name, wanted_amount) values (8, 'Wine - Beaujolais Villages', 82);
insert into hvs.product (id, name, wanted_amount) values (9, 'Mushroom - Crimini', 26);
insert into hvs.product (id, name, wanted_amount) values (10, 'Pastrami', 90);
insert into hvs.product (id, name, wanted_amount) values (11, 'Table Cloth 62x120 White', 93);
insert into hvs.product (id, name, wanted_amount) values (12, 'Potatoes - Idaho 80 Count', 50);
insert into hvs.product (id, name, wanted_amount) values (13, 'Container - Foam Dixie 12 Oz', 93);
insert into hvs.product (id, name, wanted_amount) values (14, 'Milk - 2% 250 Ml', 40);
insert into hvs.product (id, name, wanted_amount) values (15, 'Cookies - Amaretto', 49);
insert into hvs.product (id, name, wanted_amount) values (16, 'Cheese - Comtomme', 60);
insert into hvs.product (id, name, wanted_amount) values (17, 'Parsley - Dried', 65);
insert into hvs.product (id, name, wanted_amount) values (18, 'Pomello', 94);
insert into hvs.product (id, name, wanted_amount) values (19, 'Eggs - Extra Large', 39);
insert into hvs.product (id, name, wanted_amount) values (20, 'Pepper - Chilli Seeds Mild', 35);
insert into hvs.product (id, name, wanted_amount) values (21, 'Piping - Bags Quizna', 10);
insert into hvs.product (id, name, wanted_amount) values (22, 'Buffalo - Short Rib Fresh', 97);
insert into hvs.product (id, name, wanted_amount) values (23, 'Venison - Liver', 39);
insert into hvs.product (id, name, wanted_amount) values (24, 'Seedlings - Mix, Organic', 4);
insert into hvs.product (id, name, wanted_amount) values (25, 'Soup Knorr Chili With Beans', 88);
insert into hvs.product (id, name, wanted_amount) values (26, 'Bagel - Ched Chs Presliced', 2);
insert into hvs.product (id, name, wanted_amount) values (27, 'Pastry - Trippleberry Muffin - Mini', 46);
insert into hvs.product (id, name, wanted_amount) values (28, 'Stock - Fish', 52);
insert into hvs.product (id, name, wanted_amount) values (29, 'Country Roll', 87);
insert into hvs.product (id, name, wanted_amount) values (30, 'Tomato - Plum With Basil', 10);
insert into hvs.product (id, name, wanted_amount) values (31, 'Pepperoni Slices', 100);
insert into hvs.product (id, name, wanted_amount) values (32, 'Pate - Liver', 20);
insert into hvs.product (id, name, wanted_amount) values (33, 'Napkin - Beverge, White 2 - Ply', 90);
insert into hvs.product (id, name, wanted_amount) values (34, 'Gatorade - Orange', 46);
insert into hvs.product (id, name, wanted_amount) values (35, 'Beans - Fava, Canned', 12);
insert into hvs.product (id, name, wanted_amount) values (36, 'Sugar - Palm', 87);
insert into hvs.product (id, name, wanted_amount) values (37, 'Eggroll', 14);
insert into hvs.product (id, name, wanted_amount) values (38, 'Vinegar - Cider', 78);
insert into hvs.product (id, name, wanted_amount) values (39, 'Coconut - Shredded, Sweet', 18);
insert into hvs.product (id, name, wanted_amount) values (40, 'Sesame Seed Black', 7);
insert into hvs.product (id, name, wanted_amount) values (41, 'Truffle Paste', 41);
insert into hvs.product (id, name, wanted_amount) values (42, 'Peach - Fresh', 42);
insert into hvs.product (id, name, wanted_amount) values (43, 'Chutney Sauce - Mango', 8);
insert into hvs.product (id, name, wanted_amount) values (44, 'Paste - Black Olive', 34);
insert into hvs.product (id, name, wanted_amount) values (45, 'Pork - Ham, Virginia', 43);
insert into hvs.product (id, name, wanted_amount) values (46, 'Turkey Leg With Drum And Thigh', 86);
insert into hvs.product (id, name, wanted_amount) values (47, 'Monkfish Fresh - Skin Off', 17);
insert into hvs.product (id, name, wanted_amount) values (48, 'Wine - Rioja Campo Viejo', 97);
insert into hvs.product (id, name, wanted_amount) values (49, 'Langers - Mango Nectar', 20);
insert into hvs.product (id, name, wanted_amount) values (50, 'Placemat - Scallop, White', 29);
insert into hvs.product (id, name, wanted_amount) values (51, 'Muffin Mix - Chocolate Chip', 41);
insert into hvs.product (id, name, wanted_amount) values (52, 'Mix - Cappucino Cocktail', 9);
insert into hvs.product (id, name, wanted_amount) values (53, 'Pastry - Lemon Danish - Mini', 100);
insert into hvs.product (id, name, wanted_amount) values (54, 'Lotus Rootlets - Canned', 81);
insert into hvs.product (id, name, wanted_amount) values (55, 'Ecolab - Power Fusion', 7);
insert into hvs.product (id, name, wanted_amount) values (56, 'Jam - Apricot', 14);
insert into hvs.product (id, name, wanted_amount) values (57, 'Sobe - Berry Energy', 73);
insert into hvs.product (id, name, wanted_amount) values (58, 'English Muffin', 50);
insert into hvs.product (id, name, wanted_amount) values (59, 'Beer - True North Strong Ale', 71);
insert into hvs.product (id, name, wanted_amount) values (60, 'Sauce - Sesame Thai Dressing', 7);
insert into hvs.product (id, name, wanted_amount) values (61, 'Sobe - Green Tea', 71);
insert into hvs.product (id, name, wanted_amount) values (62, 'Yeast Dry - Fermipan', 31);
insert into hvs.product (id, name, wanted_amount) values (63, 'Water - Green Tea Refresher', 30);
insert into hvs.product (id, name, wanted_amount) values (64, 'Beef - Rouladin, Sliced', 77);
insert into hvs.product (id, name, wanted_amount) values (65, 'Compound - Rum', 26);
insert into hvs.product (id, name, wanted_amount) values (66, 'Glass Clear 8 Oz', 38);
insert into hvs.product (id, name, wanted_amount) values (67, 'Shrimp - Black Tiger 6 - 8', 98);
insert into hvs.product (id, name, wanted_amount) values (68, 'Samosa - Veg', 73);
insert into hvs.product (id, name, wanted_amount) values (69, 'Bread - Roll, Whole Wheat', 88);
insert into hvs.product (id, name, wanted_amount) values (70, 'Beef - Striploin Aa', 66);
insert into hvs.product (id, name, wanted_amount) values (71, 'Cheese - Cheddar, Mild', 98);
insert into hvs.product (id, name, wanted_amount) values (72, 'Puree - Raspberry', 43);
insert into hvs.product (id, name, wanted_amount) values (73, 'Pasta - Orecchiette', 99);
insert into hvs.product (id, name, wanted_amount) values (74, 'Pur Source', 11);
insert into hvs.product (id, name, wanted_amount) values (75, 'Container - Clear 16 Oz', 38);
insert into hvs.product (id, name, wanted_amount) values (76, 'Pastry - Chocolate Chip Muffin', 45);
insert into hvs.product (id, name, wanted_amount) values (77, 'Sponge Cake Mix - Chocolate', 10);
insert into hvs.product (id, name, wanted_amount) values (78, 'Nut - Almond, Blanched, Ground', 54);
insert into hvs.product (id, name, wanted_amount) values (79, 'Tart Shells - Savory, 3', 28);
insert into hvs.product (id, name, wanted_amount) values (80, 'Ice Cream - Life Savers', 94);
insert into hvs.product (id, name, wanted_amount) values (81, 'Wine - Sherry Dry Sack, William', 96);
insert into hvs.product (id, name, wanted_amount) values (82, 'Flour - Semolina', 80);
insert into hvs.product (id, name, wanted_amount) values (83, 'Carbonated Water - Blackberry', 49);
insert into hvs.product (id, name, wanted_amount) values (84, 'Onion - Dried', 2);
insert into hvs.product (id, name, wanted_amount) values (85, 'Yogurt - Raspberry, 175 Gr', 71);
insert into hvs.product (id, name, wanted_amount) values (86, 'Pastry - Lemon Danish - Mini', 14);
insert into hvs.product (id, name, wanted_amount) values (87, 'Apples - Sliced / Wedge', 89);
insert into hvs.product (id, name, wanted_amount) values (88, 'Chinese Foods - Chicken', 85);
insert into hvs.product (id, name, wanted_amount) values (89, 'Hummus - Spread', 27);
insert into hvs.product (id, name, wanted_amount) values (90, 'Asparagus - White, Canned', 19);
insert into hvs.product (id, name, wanted_amount) values (91, 'Cheese - Victor Et Berthold', 70);
insert into hvs.product (id, name, wanted_amount) values (92, 'Pasta - Spaghetti, Dry', 32);
insert into hvs.product (id, name, wanted_amount) values (93, 'Temperature Recording Station', 26);
insert into hvs.product (id, name, wanted_amount) values (94, 'Crab - Claws, 26 - 30', 5);
insert into hvs.product (id, name, wanted_amount) values (95, 'Cheese - Brie', 21);
insert into hvs.product (id, name, wanted_amount) values (96, 'Sobe - Tropical Energy', 54);
insert into hvs.product (id, name, wanted_amount) values (97, 'Coconut Milk - Unsweetened', 24);
insert into hvs.product (id, name, wanted_amount) values (98, 'Ecolab Crystal Fusion', 82);
insert into hvs.product (id, name, wanted_amount) values (99, 'Brocolinni - Gaylan, Chinese', 58);
insert into hvs.product (id, name, wanted_amount) values (100, 'Bay Leaf', 59);
insert into hvs.product (id, name, wanted_amount) values (101, 'Mushroom - Crimini', 99);
insert into hvs.product (id, name, wanted_amount) values (102, 'Napkin - Cocktail,beige 2 - Ply', 91);
insert into hvs.product (id, name, wanted_amount) values (103, 'Rhubarb', 44);
insert into hvs.product (id, name, wanted_amount) values (104, 'Pail For Lid 1537', 85);
insert into hvs.product (id, name, wanted_amount) values (105, 'Cheese - Grie Des Champ', 76);
insert into hvs.product (id, name, wanted_amount) values (106, 'Ham - Proscuitto', 78);
insert into hvs.product (id, name, wanted_amount) values (107, 'Tea - Apple Green Tea', 63);
insert into hvs.product (id, name, wanted_amount) values (108, 'Wine - Merlot Vina Carmen', 55);
insert into hvs.product (id, name, wanted_amount) values (109, 'Pears - Bosc', 18);
insert into hvs.product (id, name, wanted_amount) values (110, 'Sour Puss - Tangerine', 35);
insert into hvs.product (id, name, wanted_amount) values (111, 'Waffle Stix', 76);
insert into hvs.product (id, name, wanted_amount) values (112, 'Pie Shells 10', 14);
insert into hvs.product (id, name, wanted_amount) values (113, 'Gherkin - Sour', 100);
insert into hvs.product (id, name, wanted_amount) values (114, 'Fib N9 - Prague Powder', 89);
insert into hvs.product (id, name, wanted_amount) values (115, 'Cookies - Fortune', 30);
insert into hvs.product (id, name, wanted_amount) values (116, 'Pork - Backfat', 59);
insert into hvs.product (id, name, wanted_amount) values (117, 'Ice Cream Bar - Rolo Cone', 36);
insert into hvs.product (id, name, wanted_amount) values (118, 'Pepper - Chili Powder', 87);
insert into hvs.product (id, name, wanted_amount) values (119, 'Beans - Fava Fresh', 36);
insert into hvs.product (id, name, wanted_amount) values (120, 'Soup - Campbells Tomato Ravioli', 9);
insert into hvs.product (id, name, wanted_amount) values (121, 'Lemon Pepper', 52);
insert into hvs.product (id, name, wanted_amount) values (122, 'Pepper - Red Thai', 47);
insert into hvs.product (id, name, wanted_amount) values (123, 'Beef - Ox Tail, Frozen', 47);
insert into hvs.product (id, name, wanted_amount) values (124, 'Food Colouring - Green', 16);
insert into hvs.product (id, name, wanted_amount) values (125, 'Wine - Manischewitz Concord', 96);
insert into hvs.product (id, name, wanted_amount) values (126, 'Wine - Chateau Aqueria Tavel', 48);
insert into hvs.product (id, name, wanted_amount) values (127, 'Pepper - Cayenne', 10);
insert into hvs.product (id, name, wanted_amount) values (128, 'Crush - Grape, 355 Ml', 26);
insert into hvs.product (id, name, wanted_amount) values (129, 'Pork - Ham Hocks - Smoked', 64);
insert into hvs.product (id, name, wanted_amount) values (130, 'Veal - Eye Of Round', 98);
insert into hvs.product (id, name, wanted_amount) values (131, 'Ketchup - Tomato', 83);
insert into hvs.product (id, name, wanted_amount) values (132, 'Apron', 93);
insert into hvs.product (id, name, wanted_amount) values (133, 'Wine - White, Schroder And Schyl', 37);
insert into hvs.product (id, name, wanted_amount) values (134, 'Ice Cream - Life Savers', 90);
insert into hvs.product (id, name, wanted_amount) values (135, 'Beef - Bones, Marrow', 46);
insert into hvs.product (id, name, wanted_amount) values (136, 'Swordfish Loin Portions', 52);
insert into hvs.product (id, name, wanted_amount) values (137, 'Mushrooms - Honey', 91);
insert into hvs.product (id, name, wanted_amount) values (138, 'Filling - Mince Meat', 50);
insert into hvs.product (id, name, wanted_amount) values (139, 'Beef - Eye Of Round', 71);
insert into hvs.product (id, name, wanted_amount) values (140, 'Cocoa Powder - Dutched', 100);
insert into hvs.product (id, name, wanted_amount) values (141, 'Cake Sheet Combo Party Pack', 73);
insert into hvs.product (id, name, wanted_amount) values (142, 'Hummus - Spread', 96);
insert into hvs.product (id, name, wanted_amount) values (143, 'Juice - Clam, 46 Oz', 44);
insert into hvs.product (id, name, wanted_amount) values (144, 'Ice - Clear, 300 Lb For Carving', 52);
insert into hvs.product (id, name, wanted_amount) values (145, 'Muffin Mix - Chocolate Chip', 97);
insert into hvs.product (id, name, wanted_amount) values (146, 'Bandage - Flexible Neon', 8);
insert into hvs.product (id, name, wanted_amount) values (147, 'Flounder - Fresh', 80);
insert into hvs.product (id, name, wanted_amount) values (148, 'Green Scrubbie Pad H.duty', 75);
insert into hvs.product (id, name, wanted_amount) values (149, 'Cheese - Parmesan Grated', 30);
insert into hvs.product (id, name, wanted_amount) values (150, 'Crab - Meat', 85);
insert into hvs.product (id, name, wanted_amount) values (151, 'Shrimp - Black Tiger 8 - 12', 99);
insert into hvs.product (id, name, wanted_amount) values (152, 'Ecolab - Mikroklene 4/4 L', 9);
insert into hvs.product (id, name, wanted_amount) values (153, 'Pesto - Primerba, Paste', 6);
insert into hvs.product (id, name, wanted_amount) values (154, 'Cookie Trail Mix', 37);
insert into hvs.product (id, name, wanted_amount) values (155, 'Sesame Seed Black', 92);
insert into hvs.product (id, name, wanted_amount) values (156, 'Chicken Breast Wing On', 77);
insert into hvs.product (id, name, wanted_amount) values (157, 'Tea - Honey Green Tea', 11);
insert into hvs.product (id, name, wanted_amount) values (158, 'Beans - Black Bean, Dry', 27);
insert into hvs.product (id, name, wanted_amount) values (159, 'Cake - Pancake', 59);
insert into hvs.product (id, name, wanted_amount) values (160, 'Doilies - 8, Paper', 65);
insert into hvs.product (id, name, wanted_amount) values (161, 'Carbonated Water - Peach', 50);
insert into hvs.product (id, name, wanted_amount) values (162, 'Scotch - Queen Anne', 61);
insert into hvs.product (id, name, wanted_amount) values (163, 'Quail Eggs - Canned', 36);
insert into hvs.product (id, name, wanted_amount) values (164, 'Cheese - Blue', 63);
insert into hvs.product (id, name, wanted_amount) values (165, 'Soup - Campbells Beef Noodle', 52);
insert into hvs.product (id, name, wanted_amount) values (166, 'Crush - Cream Soda', 48);
insert into hvs.product (id, name, wanted_amount) values (167, 'Blouse / Shirt / Sweater', 10);
insert into hvs.product (id, name, wanted_amount) values (168, 'Chocolate - Pistoles, Lactee, Milk', 43);
insert into hvs.product (id, name, wanted_amount) values (169, 'Beef - Cow Feet Split', 31);
insert into hvs.product (id, name, wanted_amount) values (170, 'Bar Mix - Lemon', 48);
insert into hvs.product (id, name, wanted_amount) values (171, 'Table Cloth 81x81 Colour', 92);
insert into hvs.product (id, name, wanted_amount) values (172, 'Puree - Kiwi', 6);
insert into hvs.product (id, name, wanted_amount) values (173, 'Wine - Vineland Estate Semi - Dry', 8);
insert into hvs.product (id, name, wanted_amount) values (174, 'Squash - Pattypan, Yellow', 47);
insert into hvs.product (id, name, wanted_amount) values (175, 'Scallop - St. Jaques', 53);
insert into hvs.product (id, name, wanted_amount) values (176, 'Wonton Wrappers', 33);
insert into hvs.product (id, name, wanted_amount) values (177, 'Muffin Mix - Chocolate Chip', 85);
insert into hvs.product (id, name, wanted_amount) values (178, 'Hagen Daza - Dk Choocolate', 6);
insert into hvs.product (id, name, wanted_amount) values (179, 'Pasta - Rotini, Colour, Dry', 22);
insert into hvs.product (id, name, wanted_amount) values (180, 'Corn Shoots', 4);
insert into hvs.product (id, name, wanted_amount) values (181, 'Appetizer - Lobster Phyllo Roll', 42);
insert into hvs.product (id, name, wanted_amount) values (182, 'Truffle - Whole Black Peeled', 88);
insert into hvs.product (id, name, wanted_amount) values (183, 'Wine - Port Late Bottled Vintage', 46);
insert into hvs.product (id, name, wanted_amount) values (184, 'Sprouts - Bean', 35);
insert into hvs.product (id, name, wanted_amount) values (185, 'Shark - Loin', 40);
insert into hvs.product (id, name, wanted_amount) values (186, 'Wine - Fontanafredda Barolo', 31);
insert into hvs.product (id, name, wanted_amount) values (187, 'Rice - 7 Grain Blend', 67);
insert into hvs.product (id, name, wanted_amount) values (188, 'Quail - Jumbo', 20);
insert into hvs.product (id, name, wanted_amount) values (189, 'Venison - Denver Leg Boneless', 72);
insert into hvs.product (id, name, wanted_amount) values (190, 'Halibut - Fletches', 69);
insert into hvs.product (id, name, wanted_amount) values (191, 'Pastry - Apple Large', 14);
insert into hvs.product (id, name, wanted_amount) values (192, 'Oil - Olive, Extra Virgin', 78);
insert into hvs.product (id, name, wanted_amount) values (193, 'Beef - Striploin', 60);
insert into hvs.product (id, name, wanted_amount) values (194, 'Lid Tray - 12in Dome', 30);
insert into hvs.product (id, name, wanted_amount) values (195, 'Pepper - Gypsy Pepper', 66);
insert into hvs.product (id, name, wanted_amount) values (196, 'Mushroom - Portebello', 85);
insert into hvs.product (id, name, wanted_amount) values (197, 'Beer - Sleemans Honey Brown', 50);
insert into hvs.product (id, name, wanted_amount) values (198, 'Bread Sour Rolls', 76);
insert into hvs.product (id, name, wanted_amount) values (199, 'Flour - Strong Pizza', 39);
insert into hvs.product (id, name, wanted_amount) values (200, 'Lettuce - Mini Greens, Whole', 50);
insert into hvs.product (id, name, wanted_amount) values (201, 'Tofu - Firm', 70);
insert into hvs.product (id, name, wanted_amount) values (202, 'Jameson - Irish Whiskey', 12);
insert into hvs.product (id, name, wanted_amount) values (203, 'Veal - Inside', 72);
insert into hvs.product (id, name, wanted_amount) values (204, 'Cheese - Cheddarsliced', 49);
insert into hvs.product (id, name, wanted_amount) values (205, 'Veal - Bones', 75);
insert into hvs.product (id, name, wanted_amount) values (206, 'Olives - Morracan Dired', 3);
insert into hvs.product (id, name, wanted_amount) values (207, 'Syrup - Monin - Granny Smith', 21);
insert into hvs.product (id, name, wanted_amount) values (208, 'Shrimp - Black Tiger 16/20', 57);
insert into hvs.product (id, name, wanted_amount) values (209, 'Chutney Sauce - Mango', 54);
insert into hvs.product (id, name, wanted_amount) values (210, 'Stainless Steel Cleaner Vision', 83);
insert into hvs.product (id, name, wanted_amount) values (211, 'Coconut - Whole', 63);
insert into hvs.product (id, name, wanted_amount) values (212, 'Currants', 5);
insert into hvs.product (id, name, wanted_amount) values (213, 'Puree - Passion Fruit', 82);
insert into hvs.product (id, name, wanted_amount) values (214, 'Nantucket - Carrot Orange', 91);
insert into hvs.product (id, name, wanted_amount) values (215, 'Skirt - 29 Foot', 53);
insert into hvs.product (id, name, wanted_amount) values (216, 'Beans - French', 43);
insert into hvs.product (id, name, wanted_amount) values (217, 'Wine - Sicilia Igt Nero Avola', 13);
insert into hvs.product (id, name, wanted_amount) values (218, 'Drambuie', 66);
insert into hvs.product (id, name, wanted_amount) values (219, 'Tilapia - Fillets', 47);
insert into hvs.product (id, name, wanted_amount) values (220, 'Beans - Fava, Canned', 75);
insert into hvs.product (id, name, wanted_amount) values (221, 'Bar Nature Valley', 34);
insert into hvs.product (id, name, wanted_amount) values (222, 'Muffin - Zero Transfat', 10);
insert into hvs.product (id, name, wanted_amount) values (223, 'Horseradish Root', 21);
insert into hvs.product (id, name, wanted_amount) values (224, 'Pasta - Orecchiette', 25);
insert into hvs.product (id, name, wanted_amount) values (225, 'Energy Drink Red Bull', 26);
insert into hvs.product (id, name, wanted_amount) values (226, 'Pie Filling - Pumpkin', 6);
insert into hvs.product (id, name, wanted_amount) values (227, 'Chocolate - Milk', 21);
insert into hvs.product (id, name, wanted_amount) values (228, 'Cookie - Dough Variety', 7);
insert into hvs.product (id, name, wanted_amount) values (229, 'Pastry - Key Limepoppy Seed Tea', 15);
insert into hvs.product (id, name, wanted_amount) values (230, 'Macaroons - Homestyle Two Bit', 6);
insert into hvs.product (id, name, wanted_amount) values (231, 'Coffee Beans - Chocolate', 75);
insert into hvs.product (id, name, wanted_amount) values (232, 'Icecream Cone - Areo Chocolate', 33);
insert into hvs.product (id, name, wanted_amount) values (233, 'Squid - U - 10 Thailand', 87);
insert into hvs.product (id, name, wanted_amount) values (234, 'Ecolab - Power Fusion', 78);
insert into hvs.product (id, name, wanted_amount) values (235, 'Mints - Striped Red', 83);
insert into hvs.product (id, name, wanted_amount) values (236, 'Nori Sea Weed', 44);
insert into hvs.product (id, name, wanted_amount) values (237, 'Longos - Lasagna Veg', 6);
insert into hvs.product (id, name, wanted_amount) values (238, 'Tomatoes - Heirloom', 77);
insert into hvs.product (id, name, wanted_amount) values (239, 'Bread - Flat Bread', 93);
insert into hvs.product (id, name, wanted_amount) values (240, 'Buffalo - Short Rib Fresh', 20);
insert into hvs.product (id, name, wanted_amount) values (241, 'Couscous', 68);
insert into hvs.product (id, name, wanted_amount) values (242, 'Juice - Orange', 35);
insert into hvs.product (id, name, wanted_amount) values (243, 'Yogurt - Blueberry, 175 Gr', 13);
insert into hvs.product (id, name, wanted_amount) values (244, 'Soup - Canadian Pea, Dry Mix', 34);
insert into hvs.product (id, name, wanted_amount) values (245, 'Longos - Lasagna Veg', 80);
insert into hvs.product (id, name, wanted_amount) values (246, 'Buttons', 85);
insert into hvs.product (id, name, wanted_amount) values (247, 'Lemonade - Natural, 591 Ml', 98);
insert into hvs.product (id, name, wanted_amount) values (248, 'Salad Dressing', 15);
insert into hvs.product (id, name, wanted_amount) values (249, 'Chinese Foods - Cantonese', 7);
insert into hvs.product (id, name, wanted_amount) values (250, 'Pork - Backs - Boneless', 72);
insert into hvs.product (id, name, wanted_amount) values (251, 'Lentils - Red, Dry', 21);
insert into hvs.product (id, name, wanted_amount) values (252, 'Spice - Paprika', 45);
insert into hvs.product (id, name, wanted_amount) values (253, 'Dc Hikiage Hira Huba', 30);
insert into hvs.product (id, name, wanted_amount) values (254, 'Kiwi', 11);
insert into hvs.product (id, name, wanted_amount) values (255, 'Wine - Marlbourough Sauv Blanc', 39);
insert into hvs.product (id, name, wanted_amount) values (256, 'Coffee - Decafenated', 43);
insert into hvs.product (id, name, wanted_amount) values (257, 'Lamb Rack - Ontario', 38);
insert into hvs.product (id, name, wanted_amount) values (258, 'Tomatillo', 7);
insert into hvs.product (id, name, wanted_amount) values (259, 'Island Oasis - Peach Daiquiri', 61);
insert into hvs.product (id, name, wanted_amount) values (260, 'Basil - Seedlings Cookstown', 79);
insert into hvs.product (id, name, wanted_amount) values (261, 'Milk Powder', 95);
insert into hvs.product (id, name, wanted_amount) values (262, 'Lamb - Whole Head Off,nz', 80);
insert into hvs.product (id, name, wanted_amount) values (263, 'Chicken - Whole Roasting', 55);
insert into hvs.product (id, name, wanted_amount) values (264, 'Octopus', 26);
insert into hvs.product (id, name, wanted_amount) values (265, 'External Supplier', 28);
insert into hvs.product (id, name, wanted_amount) values (266, 'Energy - Boo - Koo', 49);
insert into hvs.product (id, name, wanted_amount) values (267, 'Sausage - Liver', 94);
insert into hvs.product (id, name, wanted_amount) values (268, 'Bread - Pumpernickle, Rounds', 80);
insert into hvs.product (id, name, wanted_amount) values (269, 'Veal - Heart', 46);
insert into hvs.product (id, name, wanted_amount) values (270, 'Flour - Chickpea', 19);
insert into hvs.product (id, name, wanted_amount) values (271, 'Cranberries - Frozen', 77);
insert into hvs.product (id, name, wanted_amount) values (272, 'Yogurt - Plain', 97);
insert into hvs.product (id, name, wanted_amount) values (273, 'Jameson - Irish Whiskey', 98);
insert into hvs.product (id, name, wanted_amount) values (274, 'Tofu - Soft', 83);
insert into hvs.product (id, name, wanted_amount) values (275, 'Whmis - Spray Bottle Trigger', 96);
insert into hvs.product (id, name, wanted_amount) values (276, 'Sprouts Dikon', 9);
insert into hvs.product (id, name, wanted_amount) values (277, 'Wine - Jackson Triggs Okonagan', 17);
insert into hvs.product (id, name, wanted_amount) values (278, 'Cherries - Frozen', 1);
insert into hvs.product (id, name, wanted_amount) values (279, 'Sugar - Cubes', 36);
insert into hvs.product (id, name, wanted_amount) values (280, 'Bread - Corn Muffaletta', 68);
insert into hvs.product (id, name, wanted_amount) values (281, 'Pork Casing', 54);
insert into hvs.product (id, name, wanted_amount) values (282, 'Glaze - Apricot', 83);
insert into hvs.product (id, name, wanted_amount) values (283, 'Flower - Commercial Spider', 38);
insert into hvs.product (id, name, wanted_amount) values (284, 'Bagel - Everything Presliced', 85);
insert into hvs.product (id, name, wanted_amount) values (285, 'Tea - Lemon Scented', 29);
insert into hvs.product (id, name, wanted_amount) values (286, 'Wasabi Powder', 66);
insert into hvs.product (id, name, wanted_amount) values (287, 'Pasta - Angel Hair', 19);
insert into hvs.product (id, name, wanted_amount) values (288, 'Orange - Tangerine', 96);
insert into hvs.product (id, name, wanted_amount) values (289, 'Dikon', 99);
insert into hvs.product (id, name, wanted_amount) values (290, 'V8 - Berry Blend', 77);
insert into hvs.product (id, name, wanted_amount) values (291, 'Coconut Milk - Unsweetened', 95);
insert into hvs.product (id, name, wanted_amount) values (292, 'Remy Red Berry Infusion', 36);
insert into hvs.product (id, name, wanted_amount) values (293, 'Island Oasis - Lemonade', 45);
insert into hvs.product (id, name, wanted_amount) values (294, 'Wine - Cousino Macul Antiguas', 64);
insert into hvs.product (id, name, wanted_amount) values (295, 'Temperature Recording Station', 23);
insert into hvs.product (id, name, wanted_amount) values (296, 'Crawfish', 5);
insert into hvs.product (id, name, wanted_amount) values (297, 'Beef - Kindney, Whole', 62);
insert into hvs.product (id, name, wanted_amount) values (298, 'Bread - Dark Rye', 27);
insert into hvs.product (id, name, wanted_amount) values (299, 'Truffle Cups - Red', 77);
insert into hvs.product (id, name, wanted_amount) values (300, 'Muffin Hinge - 211n', 8);
insert into hvs.product (id, name, wanted_amount) values (301, 'Juice - Propel Sport', 85);
insert into hvs.product (id, name, wanted_amount) values (302, 'Eggplant Oriental', 71);
insert into hvs.product (id, name, wanted_amount) values (303, 'Beef - Prime Rib Aaa', 64);
insert into hvs.product (id, name, wanted_amount) values (304, 'Dry Ice', 31);
insert into hvs.product (id, name, wanted_amount) values (305, 'Carbonated Water - Wildberry', 79);
insert into hvs.product (id, name, wanted_amount) values (306, 'Bread Base - Gold Formel', 15);
insert into hvs.product (id, name, wanted_amount) values (307, 'Momiji Oroshi Chili Sauce', 78);
insert into hvs.product (id, name, wanted_amount) values (308, 'Bread - Ciabatta Buns', 2);
insert into hvs.product (id, name, wanted_amount) values (309, 'Bread - Hamburger Buns', 43);
insert into hvs.product (id, name, wanted_amount) values (310, 'Transfer Sheets', 21);
insert into hvs.product (id, name, wanted_amount) values (311, 'Wine - Cava Aria Estate Brut', 48);
insert into hvs.product (id, name, wanted_amount) values (312, 'Asparagus - Green, Fresh', 62);
insert into hvs.product (id, name, wanted_amount) values (313, 'Sobe - Orange Carrot', 46);
insert into hvs.product (id, name, wanted_amount) values (314, 'Tea - Herbal Sweet Dreams', 38);
insert into hvs.product (id, name, wanted_amount) values (315, 'Sauce - Plum', 23);
insert into hvs.product (id, name, wanted_amount) values (316, 'Muffin Chocolate Individual Wrap', 48);
insert into hvs.product (id, name, wanted_amount) values (317, 'Piping Jelly - All Colours', 99);
insert into hvs.product (id, name, wanted_amount) values (318, 'Lemonade - Black Cherry, 591 Ml', 52);
insert into hvs.product (id, name, wanted_amount) values (319, 'Brandy - Bar', 82);
insert into hvs.product (id, name, wanted_amount) values (320, 'Thermometer Digital', 97);
insert into hvs.product (id, name, wanted_amount) values (321, 'Roe - Lump Fish, Black', 50);
insert into hvs.product (id, name, wanted_amount) values (322, 'Veal - Knuckle', 90);
insert into hvs.product (id, name, wanted_amount) values (323, 'Compound - Strawberry', 10);
insert into hvs.product (id, name, wanted_amount) values (324, 'Pie Shell - 5', 3);
insert into hvs.product (id, name, wanted_amount) values (325, 'Bread - French Baquette', 16);
insert into hvs.product (id, name, wanted_amount) values (326, 'Magnotta Bel Paese Red', 1);
insert into hvs.product (id, name, wanted_amount) values (327, 'Cookie - Oreo 100x2', 46);
insert into hvs.product (id, name, wanted_amount) values (328, 'White Fish - Filets', 42);
insert into hvs.product (id, name, wanted_amount) values (329, 'Aspic - Clear', 63);
insert into hvs.product (id, name, wanted_amount) values (330, 'Wine - Red, Cooking', 60);
insert into hvs.product (id, name, wanted_amount) values (331, 'Compound - Orange', 7);
insert into hvs.product (id, name, wanted_amount) values (332, 'Sugar - Splenda Sweetener', 84);
insert into hvs.product (id, name, wanted_amount) values (333, 'Wine - Magnotta - Cab Franc', 14);
insert into hvs.product (id, name, wanted_amount) values (334, 'Tomatoes - Grape', 20);
insert into hvs.product (id, name, wanted_amount) values (335, 'Cheese - Wine', 84);
insert into hvs.product (id, name, wanted_amount) values (336, 'Bread - Roll, Italian', 27);
insert into hvs.product (id, name, wanted_amount) values (337, 'Chicken Giblets', 81);
insert into hvs.product (id, name, wanted_amount) values (338, 'Plate Foam Laminated 9in Blk', 62);
insert into hvs.product (id, name, wanted_amount) values (339, 'Shrimp - 16/20, Iqf, Shell On', 85);
insert into hvs.product (id, name, wanted_amount) values (340, 'Cheese - Parmesan Cubes', 43);
insert into hvs.product (id, name, wanted_amount) values (341, 'Ham - Procutinni', 83);
insert into hvs.product (id, name, wanted_amount) values (342, 'Lid - 0090 Clear', 87);
insert into hvs.product (id, name, wanted_amount) values (343, 'Compound - Raspberry', 26);
insert into hvs.product (id, name, wanted_amount) values (344, 'Onion Powder', 9);
insert into hvs.product (id, name, wanted_amount) values (345, 'Shrimp - Baby, Cold Water', 29);
insert into hvs.product (id, name, wanted_amount) values (346, 'Foam Dinner Plate', 82);
insert into hvs.product (id, name, wanted_amount) values (347, 'Banana Turning', 22);
insert into hvs.product (id, name, wanted_amount) values (348, 'Ham - Proscuitto', 18);
insert into hvs.product (id, name, wanted_amount) values (349, 'Pasta - Penne, Rigate, Dry', 20);
insert into hvs.product (id, name, wanted_amount) values (350, 'Cheese - Taleggio D.o.p.', 59);
insert into hvs.product (id, name, wanted_amount) values (351, 'Veal - Liver', 43);
insert into hvs.product (id, name, wanted_amount) values (352, 'Liners - Baking Cups', 74);
insert into hvs.product (id, name, wanted_amount) values (353, 'Red Currants', 25);
insert into hvs.product (id, name, wanted_amount) values (354, 'Liqueur Banana, Ramazzotti', 27);
insert into hvs.product (id, name, wanted_amount) values (355, 'Steel Wool', 4);
insert into hvs.product (id, name, wanted_amount) values (356, 'Bulgar', 81);
insert into hvs.product (id, name, wanted_amount) values (357, 'Parsley - Dried', 50);
insert into hvs.product (id, name, wanted_amount) values (358, 'Veal - Kidney', 68);
insert into hvs.product (id, name, wanted_amount) values (359, 'Cumin - Ground', 90);
insert into hvs.product (id, name, wanted_amount) values (360, 'Worcestershire Sauce', 5);
insert into hvs.product (id, name, wanted_amount) values (361, 'Pastry - Baked Cinnamon Stick', 28);
insert into hvs.product (id, name, wanted_amount) values (362, 'Cake - French Pear Tart', 44);
insert into hvs.product (id, name, wanted_amount) values (363, 'Cheese - Ermite Bleu', 42);
insert into hvs.product (id, name, wanted_amount) values (364, 'Dehydrated Kelp Kombo', 22);
insert into hvs.product (id, name, wanted_amount) values (365, 'Beer - Blue', 59);
insert into hvs.product (id, name, wanted_amount) values (366, 'Compound - Strawberry', 53);
insert into hvs.product (id, name, wanted_amount) values (367, 'Onions - Spanish', 89);
insert into hvs.product (id, name, wanted_amount) values (368, 'Initation Crab Meat', 9);
insert into hvs.product (id, name, wanted_amount) values (369, 'Oxtail - Cut', 62);
insert into hvs.product (id, name, wanted_amount) values (370, 'Veal - Inside Round / Top, Lean', 1);
insert into hvs.product (id, name, wanted_amount) values (371, 'Aspic - Amber', 70);
insert into hvs.product (id, name, wanted_amount) values (372, 'Pasta - Linguini, Dry', 85);
insert into hvs.product (id, name, wanted_amount) values (373, 'Crush - Grape, 355 Ml', 65);
insert into hvs.product (id, name, wanted_amount) values (374, 'Nestea - Iced Tea', 81);
insert into hvs.product (id, name, wanted_amount) values (375, 'Lamb - Whole, Frozen', 87);
insert into hvs.product (id, name, wanted_amount) values (376, 'Oil - Canola', 5);
insert into hvs.product (id, name, wanted_amount) values (377, 'Scallops - U - 10', 40);
insert into hvs.product (id, name, wanted_amount) values (378, 'Apple - Fuji', 37);
insert into hvs.product (id, name, wanted_amount) values (379, 'Sage Derby', 61);
insert into hvs.product (id, name, wanted_amount) values (380, 'Beans - Soya Bean', 2);
insert into hvs.product (id, name, wanted_amount) values (381, 'Cocktail Napkin Blue', 22);
insert into hvs.product (id, name, wanted_amount) values (382, 'Soup - Campbells, Butternut', 52);
insert into hvs.product (id, name, wanted_amount) values (383, 'Sauce - Apple, Unsweetened', 59);
insert into hvs.product (id, name, wanted_amount) values (384, 'Mushroom - King Eryingii', 93);
insert into hvs.product (id, name, wanted_amount) values (385, 'Flour - Chickpea', 53);
insert into hvs.product (id, name, wanted_amount) values (386, 'Roe - White Fish', 12);
insert into hvs.product (id, name, wanted_amount) values (387, 'Sesame Seed Black', 52);
insert into hvs.product (id, name, wanted_amount) values (388, 'Turkey - Ground. Lean', 21);
insert into hvs.product (id, name, wanted_amount) values (389, 'Ecolab - Balanced Fusion', 58);
insert into hvs.product (id, name, wanted_amount) values (390, 'Icecream Cone - Areo Chocolate', 36);
insert into hvs.product (id, name, wanted_amount) values (391, 'Corn - Mini', 53);
insert into hvs.product (id, name, wanted_amount) values (392, 'Beer - Pilsner Urquell', 77);
insert into hvs.product (id, name, wanted_amount) values (393, 'Tomato - Peeled Italian Canned', 63);
insert into hvs.product (id, name, wanted_amount) values (394, 'Squid - Breaded', 65);
insert into hvs.product (id, name, wanted_amount) values (395, 'Fish - Base, Bouillion', 93);
insert into hvs.product (id, name, wanted_amount) values (396, 'Wine - Coteaux Du Tricastin Ac', 50);
insert into hvs.product (id, name, wanted_amount) values (397, 'Wine - Fontanafredda Barolo', 78);
insert into hvs.product (id, name, wanted_amount) values (398, 'Cauliflower', 40);
insert into hvs.product (id, name, wanted_amount) values (399, 'Cherries - Frozen', 27);
insert into hvs.product (id, name, wanted_amount) values (400, 'Squash - Sunburst', 95);
insert into hvs.product (id, name, wanted_amount) values (401, 'Carbonated Water - Orange', 66);
insert into hvs.product (id, name, wanted_amount) values (402, 'Grenadine', 99);
insert into hvs.product (id, name, wanted_amount) values (403, 'Potatoes - Purple, Organic', 14);
insert into hvs.product (id, name, wanted_amount) values (404, 'Bread - Bagels, Plain', 95);
insert into hvs.product (id, name, wanted_amount) values (405, 'Lamb - Shanks', 87);
insert into hvs.product (id, name, wanted_amount) values (406, 'Crackers - Water', 87);
insert into hvs.product (id, name, wanted_amount) values (407, 'Versatainer Nc - 888', 11);
insert into hvs.product (id, name, wanted_amount) values (408, 'Loaf Pan - 2 Lb, Foil', 66);
insert into hvs.product (id, name, wanted_amount) values (409, 'Muffin Hinge Container 6', 41);
insert into hvs.product (id, name, wanted_amount) values (410, 'Macaroons - Homestyle Two Bit', 79);
insert into hvs.product (id, name, wanted_amount) values (411, 'Doilies - 12, Paper', 61);
insert into hvs.product (id, name, wanted_amount) values (412, 'Myers Planters Punch', 57);
insert into hvs.product (id, name, wanted_amount) values (413, 'Wine - Red, Pelee Island Merlot', 56);
insert into hvs.product (id, name, wanted_amount) values (414, 'Cherries - Maraschino,jar', 65);
insert into hvs.product (id, name, wanted_amount) values (415, 'Wine - Chardonnay Mondavi', 53);
insert into hvs.product (id, name, wanted_amount) values (416, 'Garam Marsala', 76);
insert into hvs.product (id, name, wanted_amount) values (417, 'Cake - Cheese Cake 9 Inch', 93);
insert into hvs.product (id, name, wanted_amount) values (418, 'Coconut Milk - Unsweetened', 84);
insert into hvs.product (id, name, wanted_amount) values (419, 'Mace Ground', 43);
insert into hvs.product (id, name, wanted_amount) values (420, 'Soup - Beef, Base Mix', 25);
insert into hvs.product (id, name, wanted_amount) values (421, 'Goat - Whole Cut', 96);
insert into hvs.product (id, name, wanted_amount) values (422, 'Milkettes - 2%', 98);
insert into hvs.product (id, name, wanted_amount) values (423, 'Pasta - Lasagne, Fresh', 70);
insert into hvs.product (id, name, wanted_amount) values (424, 'Water - Green Tea Refresher', 58);
insert into hvs.product (id, name, wanted_amount) values (425, 'Pork Salted Bellies', 90);
insert into hvs.product (id, name, wanted_amount) values (426, 'Coffee - Colombian, Portioned', 1);
insert into hvs.product (id, name, wanted_amount) values (427, 'Fudge - Chocolate Fudge', 67);
insert into hvs.product (id, name, wanted_amount) values (428, 'Scallops - In Shell', 74);
insert into hvs.product (id, name, wanted_amount) values (429, 'Macaroons - Homestyle Two Bit', 18);
insert into hvs.product (id, name, wanted_amount) values (430, 'Lamb - Shoulder, Boneless', 57);
insert into hvs.product (id, name, wanted_amount) values (431, 'Extract - Rum', 89);
insert into hvs.product (id, name, wanted_amount) values (432, 'Wine - Cotes Du Rhone', 84);
insert into hvs.product (id, name, wanted_amount) values (433, 'Jameson - Irish Whiskey', 66);
insert into hvs.product (id, name, wanted_amount) values (434, 'Beans - Fava Fresh', 95);
insert into hvs.product (id, name, wanted_amount) values (435, 'Wine - Ej Gallo Sierra Valley', 77);
insert into hvs.product (id, name, wanted_amount) values (436, 'Bread - English Muffin', 78);
insert into hvs.product (id, name, wanted_amount) values (437, 'Bagels Poppyseed', 52);
insert into hvs.product (id, name, wanted_amount) values (438, 'Yogurt - French Vanilla', 70);
insert into hvs.product (id, name, wanted_amount) values (439, 'Pork - Kidney', 81);
insert into hvs.product (id, name, wanted_amount) values (440, 'Glass - Wine, Plastic, Clear 5 Oz', 71);
insert into hvs.product (id, name, wanted_amount) values (441, 'Wine - Conde De Valdemar', 40);
insert into hvs.product (id, name, wanted_amount) values (442, 'Wine - Barbera Alba Doc 2001', 60);
insert into hvs.product (id, name, wanted_amount) values (443, 'Muffin - Zero Transfat', 93);
insert into hvs.product (id, name, wanted_amount) values (444, 'Godiva White Chocolate', 60);
insert into hvs.product (id, name, wanted_amount) values (445, 'Table Cloth 72x144 White', 49);
insert into hvs.product (id, name, wanted_amount) values (446, 'Plasticforkblack', 19);
insert into hvs.product (id, name, wanted_amount) values (447, 'Wine - Red, Metus Rose', 10);
insert into hvs.product (id, name, wanted_amount) values (448, 'Puff Pastry - Sheets', 77);
insert into hvs.product (id, name, wanted_amount) values (449, 'Plums - Red', 63);
insert into hvs.product (id, name, wanted_amount) values (450, 'Chutney Sauce - Mango', 27);
insert into hvs.product (id, name, wanted_amount) values (451, 'Ham - Cooked', 5);
insert into hvs.product (id, name, wanted_amount) values (452, 'Mushroom - Morels, Dry', 17);
insert into hvs.product (id, name, wanted_amount) values (453, 'C - Plus, Orange', 5);
insert into hvs.product (id, name, wanted_amount) values (454, 'Wine - White, Mosel Gold', 8);
insert into hvs.product (id, name, wanted_amount) values (455, 'Tea - English Breakfast', 99);
insert into hvs.product (id, name, wanted_amount) values (456, 'Pepper - Chili Powder', 14);
insert into hvs.product (id, name, wanted_amount) values (457, 'Kellogs All Bran Bars', 12);
insert into hvs.product (id, name, wanted_amount) values (458, 'Bread - Italian Sesame Poly', 51);
insert into hvs.product (id, name, wanted_amount) values (459, 'Alize Red Passion', 8);
insert into hvs.product (id, name, wanted_amount) values (460, 'Gingerale - Diet - Schweppes', 35);
insert into hvs.product (id, name, wanted_amount) values (461, 'Wine - Lamancha Do Crianza', 22);
insert into hvs.product (id, name, wanted_amount) values (462, 'Mint - Fresh', 85);
insert into hvs.product (id, name, wanted_amount) values (463, 'Sauce - Plum', 53);
insert into hvs.product (id, name, wanted_amount) values (464, 'Ketchup - Tomato', 18);
insert into hvs.product (id, name, wanted_amount) values (465, 'Salmon Steak - Cohoe 8 Oz', 26);
insert into hvs.product (id, name, wanted_amount) values (466, 'Butter Ripple - Phillips', 53);
insert into hvs.product (id, name, wanted_amount) values (467, 'Bag - Regular Kraft 20 Lb', 100);
insert into hvs.product (id, name, wanted_amount) values (468, 'Cheese - Cheddar, Old White', 53);
insert into hvs.product (id, name, wanted_amount) values (469, 'Bar Mix - Lemon', 88);
insert into hvs.product (id, name, wanted_amount) values (470, 'Tomatoes - Plum, Canned', 24);
insert into hvs.product (id, name, wanted_amount) values (471, 'Seaweed Green Sheets', 67);
insert into hvs.product (id, name, wanted_amount) values (472, 'Pie Pecan', 51);
insert into hvs.product (id, name, wanted_amount) values (473, 'Lotus Root', 43);
insert into hvs.product (id, name, wanted_amount) values (474, 'Garam Masala Powder', 54);
insert into hvs.product (id, name, wanted_amount) values (475, 'Jam - Blackberry, 20 Ml Jar', 21);
insert into hvs.product (id, name, wanted_amount) values (476, 'Wine - Segura Viudas Aria Brut', 66);
insert into hvs.product (id, name, wanted_amount) values (477, 'Soup Campbells Turkey Veg.', 28);
insert into hvs.product (id, name, wanted_amount) values (478, 'Kirsch - Schloss', 17);
insert into hvs.product (id, name, wanted_amount) values (479, 'Pineapple - Regular', 6);
insert into hvs.product (id, name, wanted_amount) values (480, 'Cabbage - Savoy', 93);
insert into hvs.product (id, name, wanted_amount) values (481, 'Wine - Tribal Sauvignon', 22);
insert into hvs.product (id, name, wanted_amount) values (482, 'Nestea - Ice Tea, Diet', 53);
insert into hvs.product (id, name, wanted_amount) values (483, 'Juice - Mango', 68);
insert into hvs.product (id, name, wanted_amount) values (484, 'Shrimp - Black Tiger 16/20', 47);
insert into hvs.product (id, name, wanted_amount) values (485, 'Bacardi Raspberry', 27);
insert into hvs.product (id, name, wanted_amount) values (486, 'Beans - Wax', 87);
insert into hvs.product (id, name, wanted_amount) values (487, 'Beans - Kidney, Red Dry', 61);
insert into hvs.product (id, name, wanted_amount) values (488, 'Assorted Desserts', 43);
insert into hvs.product (id, name, wanted_amount) values (489, 'Cheese - Brick With Pepper', 60);
insert into hvs.product (id, name, wanted_amount) values (490, 'Potatoes - Peeled', 85);
insert into hvs.product (id, name, wanted_amount) values (491, 'Ecolab - Orange Frc, Cleaner', 59);
insert into hvs.product (id, name, wanted_amount) values (492, 'Doilies - 8, Paper', 98);
insert into hvs.product (id, name, wanted_amount) values (493, 'Beef - Inside Round', 62);
insert into hvs.product (id, name, wanted_amount) values (494, 'Bag - Clear 7 Lb', 89);
insert into hvs.product (id, name, wanted_amount) values (495, 'Veal - Tenderloin, Untrimmed', 37);
insert into hvs.product (id, name, wanted_amount) values (496, 'Pork Loin Bine - In Frenched', 15);
insert into hvs.product (id, name, wanted_amount) values (497, 'Wine - Coteaux Du Tricastin Ac', 94);
insert into hvs.product (id, name, wanted_amount) values (498, 'Egg Patty Fried', 80);
insert into hvs.product (id, name, wanted_amount) values (499, 'Chicken - Ground', 95);
insert into hvs.product (id, name, wanted_amount) values (500, 'Jolt Cola', 63);
insert into hvs.product (id, name, wanted_amount) values (501, 'Sour Puss Raspberry', 61);
insert into hvs.product (id, name, wanted_amount) values (502, 'Tomatoes - Cherry, Yellow', 20);
insert into hvs.product (id, name, wanted_amount) values (503, 'Energy Drink - Redbull 355ml', 79);
insert into hvs.product (id, name, wanted_amount) values (504, 'Lemonade - Kiwi, 591 Ml', 46);
insert into hvs.product (id, name, wanted_amount) values (505, 'Sugar - Monocystal / Rock', 4);
insert into hvs.product (id, name, wanted_amount) values (506, 'Apricots Fresh', 20);
insert into hvs.product (id, name, wanted_amount) values (507, 'Tart Shells - Barquettes, Savory', 13);
insert into hvs.product (id, name, wanted_amount) values (508, 'Bread Ww Cluster', 21);
insert into hvs.product (id, name, wanted_amount) values (509, 'Rice - Long Grain', 67);
insert into hvs.product (id, name, wanted_amount) values (510, 'Chicken Breast Wing On', 23);
insert into hvs.product (id, name, wanted_amount) values (511, 'Island Oasis - Lemonade', 86);
insert into hvs.product (id, name, wanted_amount) values (512, 'Beef - Roasted, Cooked', 6);
insert into hvs.product (id, name, wanted_amount) values (513, 'Dried Cherries', 46);
insert into hvs.product (id, name, wanted_amount) values (514, 'Guava', 58);
insert into hvs.product (id, name, wanted_amount) values (515, 'Onion Powder', 65);
insert into hvs.product (id, name, wanted_amount) values (516, 'Soup - Campbells Chili', 94);
insert into hvs.product (id, name, wanted_amount) values (517, 'Nut - Cashews, Whole, Raw', 16);
insert into hvs.product (id, name, wanted_amount) values (518, 'Milk - Homo', 71);
insert into hvs.product (id, name, wanted_amount) values (519, 'Cup - Translucent 7 Oz Clear', 96);
insert into hvs.product (id, name, wanted_amount) values (520, 'Soup - Campbells, Cream Of', 54);
insert into hvs.product (id, name, wanted_amount) values (521, 'Sauce - Bernaise, Mix', 17);
insert into hvs.product (id, name, wanted_amount) values (522, 'Compound - Passion Fruit', 59);
insert into hvs.product (id, name, wanted_amount) values (523, 'Bar Mix - Pina Colada, 355 Ml', 30);
insert into hvs.product (id, name, wanted_amount) values (524, 'Lid Tray - 12in Dome', 51);
insert into hvs.product (id, name, wanted_amount) values (525, 'Oil - Coconut', 11);
insert into hvs.product (id, name, wanted_amount) values (526, 'Chevril', 84);
insert into hvs.product (id, name, wanted_amount) values (527, 'Rum - Light, Captain Morgan', 2);
insert into hvs.product (id, name, wanted_amount) values (528, 'Compound - Mocha', 11);
insert into hvs.product (id, name, wanted_amount) values (529, 'Coffee - Flavoured', 60);
insert into hvs.product (id, name, wanted_amount) values (530, 'Beef - Kobe Striploin', 59);
insert into hvs.product (id, name, wanted_amount) values (531, 'Wine - Touraine Azay - Le - Rideau', 35);
insert into hvs.product (id, name, wanted_amount) values (532, 'Wine - Sauvignon Blanc', 89);
insert into hvs.product (id, name, wanted_amount) values (533, 'Cup - 3.5oz, Foam', 54);
insert into hvs.product (id, name, wanted_amount) values (534, 'Muffin Mix - Corn Harvest', 54);
insert into hvs.product (id, name, wanted_amount) values (535, 'Rum - White, Gg White', 5);
insert into hvs.product (id, name, wanted_amount) values (536, 'Knife Plastic - White', 43);
insert into hvs.product (id, name, wanted_amount) values (537, 'Pie Shells 10', 95);
insert into hvs.product (id, name, wanted_amount) values (538, 'Russian Prince', 66);
insert into hvs.product (id, name, wanted_amount) values (539, 'Pears - Bartlett', 98);
insert into hvs.product (id, name, wanted_amount) values (540, 'Hot Chocolate - Individual', 27);
insert into hvs.product (id, name, wanted_amount) values (541, 'Mushroom - Enoki, Dry', 10);
insert into hvs.product (id, name, wanted_amount) values (542, 'Wine - White, Lindemans Bin 95', 20);
insert into hvs.product (id, name, wanted_amount) values (543, 'Mushroom - Morels, Dry', 14);
insert into hvs.product (id, name, wanted_amount) values (544, 'Liqueur Banana, Ramazzotti', 60);
insert into hvs.product (id, name, wanted_amount) values (545, 'Cornflakes', 28);
insert into hvs.product (id, name, wanted_amount) values (546, 'Flour - Rye', 27);
insert into hvs.product (id, name, wanted_amount) values (547, 'Mcgillicuddy Vanilla Schnap', 45);
insert into hvs.product (id, name, wanted_amount) values (548, 'Sauce - Plum', 50);
insert into hvs.product (id, name, wanted_amount) values (549, 'Bread - Raisin', 70);
insert into hvs.product (id, name, wanted_amount) values (550, 'Lamb Leg - Bone - In Nz', 88);
insert into hvs.product (id, name, wanted_amount) values (551, 'Godiva White Chocolate', 54);
insert into hvs.product (id, name, wanted_amount) values (552, 'Foil Wrap', 38);
insert into hvs.product (id, name, wanted_amount) values (553, 'Cheese - Comte', 64);
insert into hvs.product (id, name, wanted_amount) values (554, 'Wine - Fino Tio Pepe Gonzalez', 96);
insert into hvs.product (id, name, wanted_amount) values (555, 'Carrots - Mini, Stem On', 2);
insert into hvs.product (id, name, wanted_amount) values (556, 'Pork - Belly Fresh', 68);
insert into hvs.product (id, name, wanted_amount) values (557, 'Table Cloth 81x81 Colour', 44);
insert into hvs.product (id, name, wanted_amount) values (558, 'Okra', 69);
insert into hvs.product (id, name, wanted_amount) values (559, 'Wine - Blue Nun Qualitatswein', 49);
insert into hvs.product (id, name, wanted_amount) values (560, 'Soup - French Can Pea', 64);
insert into hvs.product (id, name, wanted_amount) values (561, 'Sobe - Tropical Energy', 15);
insert into hvs.product (id, name, wanted_amount) values (562, 'Coffee - Colombian, Portioned', 94);
insert into hvs.product (id, name, wanted_amount) values (563, 'Cleaner - Comet', 6);
insert into hvs.product (id, name, wanted_amount) values (564, 'Wine - Vouvray Cuvee Domaine', 90);
insert into hvs.product (id, name, wanted_amount) values (565, 'Vinegar - Cider', 52);
insert into hvs.product (id, name, wanted_amount) values (566, 'Worcestershire Sauce', 99);
insert into hvs.product (id, name, wanted_amount) values (567, 'Onions Granulated', 97);
insert into hvs.product (id, name, wanted_amount) values (568, 'Flour - So Mix Cake White', 4);
insert into hvs.product (id, name, wanted_amount) values (569, 'Soup - Boston Clam Chowder', 78);
insert into hvs.product (id, name, wanted_amount) values (570, 'Wine - Champagne Brut Veuve', 36);
insert into hvs.product (id, name, wanted_amount) values (571, 'Bamboo Shoots - Sliced', 95);
insert into hvs.product (id, name, wanted_amount) values (572, 'Whmis Spray Bottle Graduated', 78);
insert into hvs.product (id, name, wanted_amount) values (573, 'Table Cloth 62x114 Colour', 70);
insert into hvs.product (id, name, wanted_amount) values (574, 'Kiwi', 72);
insert into hvs.product (id, name, wanted_amount) values (575, 'Bread - Bistro Sour', 13);
insert into hvs.product (id, name, wanted_amount) values (576, 'Kellogs Raisan Bran Bars', 85);
insert into hvs.product (id, name, wanted_amount) values (577, 'Goat - Leg', 93);
insert into hvs.product (id, name, wanted_amount) values (578, 'Spice - Montreal Steak Spice', 24);
insert into hvs.product (id, name, wanted_amount) values (579, 'Beets - Golden', 77);
insert into hvs.product (id, name, wanted_amount) values (580, 'Mountain Dew', 44);
insert into hvs.product (id, name, wanted_amount) values (581, 'Cake - Night And Day Choclate', 41);
insert into hvs.product (id, name, wanted_amount) values (582, 'Bread - Crumbs, Bulk', 82);
insert into hvs.product (id, name, wanted_amount) values (583, 'Wine - Prosecco Valdobienne', 40);
insert into hvs.product (id, name, wanted_amount) values (584, 'Dragon Fruit', 34);
insert into hvs.product (id, name, wanted_amount) values (585, 'Grouper - Fresh', 90);
insert into hvs.product (id, name, wanted_amount) values (586, 'Celery', 66);
insert into hvs.product (id, name, wanted_amount) values (587, 'Hersey Shakes', 74);
insert into hvs.product (id, name, wanted_amount) values (588, 'Beef - Top Butt Aaa', 45);
insert into hvs.product (id, name, wanted_amount) values (589, 'Pastry - French Mini Assorted', 31);
insert into hvs.product (id, name, wanted_amount) values (590, 'Bread Crumbs - Japanese Style', 32);
insert into hvs.product (id, name, wanted_amount) values (591, 'Wine - Red, Antinori Santa', 36);
insert into hvs.product (id, name, wanted_amount) values (592, 'Cattail Hearts', 99);
insert into hvs.product (id, name, wanted_amount) values (593, 'Foam Tray S2', 54);
insert into hvs.product (id, name, wanted_amount) values (594, 'Tomatoes - Vine Ripe, Yellow', 62);
insert into hvs.product (id, name, wanted_amount) values (595, 'Wine - Vidal Icewine Magnotta', 87);
insert into hvs.product (id, name, wanted_amount) values (596, 'Wine - White, Mosel Gold', 81);
insert into hvs.product (id, name, wanted_amount) values (597, 'Beer - Fruli', 39);
insert into hvs.product (id, name, wanted_amount) values (598, 'Chinese Foods - Pepper Beef', 9);
insert into hvs.product (id, name, wanted_amount) values (599, 'Wine - Segura Viudas Aria Brut', 11);
insert into hvs.product (id, name, wanted_amount) values (600, 'Wine - Sherry Dry Sack, William', 5);
insert into hvs.product (id, name, wanted_amount) values (601, 'Hand Towel', 23);
insert into hvs.product (id, name, wanted_amount) values (602, 'Wine - Beaujolais Villages', 45);
insert into hvs.product (id, name, wanted_amount) values (603, 'Wine - White, Riesling, Henry Of', 98);
insert into hvs.product (id, name, wanted_amount) values (604, 'Veal - Knuckle', 73);
insert into hvs.product (id, name, wanted_amount) values (605, 'Trout - Rainbow, Fresh', 43);
insert into hvs.product (id, name, wanted_amount) values (606, 'Tray - Foam, Square 4 - S', 61);
insert into hvs.product (id, name, wanted_amount) values (607, 'Sprouts - Alfalfa', 73);
insert into hvs.product (id, name, wanted_amount) values (608, 'Beef - Tongue, Fresh', 86);
insert into hvs.product (id, name, wanted_amount) values (609, 'Pastry - Baked Cinnamon Stick', 21);
insert into hvs.product (id, name, wanted_amount) values (610, 'Trout - Rainbow, Fresh', 46);
insert into hvs.product (id, name, wanted_amount) values (611, 'Bread - Rolls, Rye', 93);
insert into hvs.product (id, name, wanted_amount) values (612, 'Table Cloth 81x81 White', 9);
insert into hvs.product (id, name, wanted_amount) values (613, 'Coffee - Almond Amaretto', 52);
insert into hvs.product (id, name, wanted_amount) values (614, 'Soup Campbells Beef With Veg', 13);
insert into hvs.product (id, name, wanted_amount) values (615, 'Pork - Butt, Boneless', 56);
insert into hvs.product (id, name, wanted_amount) values (616, 'Bread - Pumpernickel', 60);
insert into hvs.product (id, name, wanted_amount) values (617, 'Beets - Golden', 97);
insert into hvs.product (id, name, wanted_amount) values (618, 'Cleaner - Lime Away', 98);
insert into hvs.product (id, name, wanted_amount) values (619, 'Squid - U - 10 Thailand', 15);
insert into hvs.product (id, name, wanted_amount) values (620, 'Beef - Rib Eye Aaa', 84);
insert into hvs.product (id, name, wanted_amount) values (621, 'Wine - Magnotta - Cab Sauv', 17);
insert into hvs.product (id, name, wanted_amount) values (622, 'Eel - Smoked', 74);
insert into hvs.product (id, name, wanted_amount) values (623, 'Dr. Pepper - 355ml', 16);
insert into hvs.product (id, name, wanted_amount) values (624, 'Wood Chips - Regular', 73);
insert into hvs.product (id, name, wanted_amount) values (625, 'Raisin - Golden', 19);
insert into hvs.product (id, name, wanted_amount) values (626, 'Bread - White Epi Baguette', 57);
insert into hvs.product (id, name, wanted_amount) values (627, 'Scallops - 10/20', 42);
insert into hvs.product (id, name, wanted_amount) values (628, 'Veal - Insides, Grains', 72);
insert into hvs.product (id, name, wanted_amount) values (629, 'Snapple Lemon Tea', 6);
insert into hvs.product (id, name, wanted_amount) values (630, 'Sole - Fillet', 73);
insert into hvs.product (id, name, wanted_amount) values (631, 'Squash - Guords', 82);
insert into hvs.product (id, name, wanted_amount) values (632, 'Salmon - Sockeye Raw', 35);
insert into hvs.product (id, name, wanted_amount) values (633, 'Wine - Red, Antinori Santa', 74);
insert into hvs.product (id, name, wanted_amount) values (634, 'Pork - European Side Bacon', 81);
insert into hvs.product (id, name, wanted_amount) values (635, 'Paste - Black Olive', 29);
insert into hvs.product (id, name, wanted_amount) values (636, 'Drambuie', 44);
insert into hvs.product (id, name, wanted_amount) values (637, 'Pie Shell - 5', 98);
insert into hvs.product (id, name, wanted_amount) values (638, 'Rabbit - Frozen', 42);
insert into hvs.product (id, name, wanted_amount) values (639, 'Duck - Legs', 81);
insert into hvs.product (id, name, wanted_amount) values (640, 'Bread Base - Gold Formel', 20);
insert into hvs.product (id, name, wanted_amount) values (641, 'Green Tea Refresher', 38);
insert into hvs.product (id, name, wanted_amount) values (642, 'Langers - Ruby Red Grapfruit', 11);
insert into hvs.product (id, name, wanted_amount) values (643, 'Coffee - Colombian, Portioned', 48);
insert into hvs.product (id, name, wanted_amount) values (644, 'Avocado', 88);
insert into hvs.product (id, name, wanted_amount) values (645, 'Wine - Red, Marechal Foch', 31);
insert into hvs.product (id, name, wanted_amount) values (646, 'Butter Balls Salted', 13);
insert into hvs.product (id, name, wanted_amount) values (647, 'Emulsifier', 15);
insert into hvs.product (id, name, wanted_amount) values (648, 'Sausage - Meat', 48);
insert into hvs.product (id, name, wanted_amount) values (649, 'Vermouth - Sweet, Cinzano', 38);
insert into hvs.product (id, name, wanted_amount) values (650, 'Cheese - Brick With Onion', 11);
insert into hvs.product (id, name, wanted_amount) values (651, 'Molasses - Fancy', 86);
insert into hvs.product (id, name, wanted_amount) values (652, 'Beef - Eye Of Round', 96);
insert into hvs.product (id, name, wanted_amount) values (653, 'Trout - Rainbow, Fresh', 25);
insert into hvs.product (id, name, wanted_amount) values (654, 'Muffin Batt - Blueberry Passion', 6);
insert into hvs.product (id, name, wanted_amount) values (655, 'Juice - V8 Splash', 14);
insert into hvs.product (id, name, wanted_amount) values (656, 'Beans - Fine', 60);
insert into hvs.product (id, name, wanted_amount) values (657, 'Vaccum Bag - 14x20', 61);
insert into hvs.product (id, name, wanted_amount) values (658, 'Juice - Clam, 46 Oz', 3);
insert into hvs.product (id, name, wanted_amount) values (659, 'Bamboo Shoots - Sliced', 90);
insert into hvs.product (id, name, wanted_amount) values (660, 'Muffin Hinge Container 6', 28);
insert into hvs.product (id, name, wanted_amount) values (661, 'Vol Au Vents', 1);
insert into hvs.product (id, name, wanted_amount) values (662, 'Calaloo', 43);
insert into hvs.product (id, name, wanted_amount) values (663, 'Nestea - Iced Tea', 2);
insert into hvs.product (id, name, wanted_amount) values (664, 'Kaffir Lime Leaves', 84);
insert into hvs.product (id, name, wanted_amount) values (665, 'Potato - Sweet', 7);
insert into hvs.product (id, name, wanted_amount) values (666, 'Isomalt', 84);
insert into hvs.product (id, name, wanted_amount) values (667, 'Sparkling Wine - Rose, Freixenet', 35);
insert into hvs.product (id, name, wanted_amount) values (668, 'Pork - Ham Hocks - Smoked', 73);
insert into hvs.product (id, name, wanted_amount) values (669, 'Pastry - Raisin Muffin - Mini', 86);
insert into hvs.product (id, name, wanted_amount) values (670, 'Tomatoes - Yellow Hot House', 4);
insert into hvs.product (id, name, wanted_amount) values (671, 'Juice - Orange, Concentrate', 61);
insert into hvs.product (id, name, wanted_amount) values (672, 'Pork - Sausage, Medium', 16);
insert into hvs.product (id, name, wanted_amount) values (673, 'Veal - Knuckle', 89);
insert into hvs.product (id, name, wanted_amount) values (674, 'Scotch - Queen Anne', 25);
insert into hvs.product (id, name, wanted_amount) values (675, 'Daves Island Stinger', 77);
insert into hvs.product (id, name, wanted_amount) values (676, 'Bandage - Fexible 1x3', 43);
insert into hvs.product (id, name, wanted_amount) values (677, 'Bread - Flat Bread', 35);
insert into hvs.product (id, name, wanted_amount) values (678, 'Juice - V8, Tomato', 37);
insert into hvs.product (id, name, wanted_amount) values (679, 'Wine - Champagne Brut Veuve', 48);
insert into hvs.product (id, name, wanted_amount) values (680, 'Lentils - Green, Dry', 18);
insert into hvs.product (id, name, wanted_amount) values (681, 'Corn - Mini', 97);
insert into hvs.product (id, name, wanted_amount) values (682, 'Eggplant Oriental', 30);
insert into hvs.product (id, name, wanted_amount) values (683, 'Chips - Assorted', 16);
insert into hvs.product (id, name, wanted_amount) values (684, 'Tilapia - Fillets', 40);
insert into hvs.product (id, name, wanted_amount) values (685, 'Rum - Coconut, Malibu', 23);
insert into hvs.product (id, name, wanted_amount) values (686, 'Muffin - Zero Transfat', 23);
insert into hvs.product (id, name, wanted_amount) values (687, 'Wine - Red, Lurton Merlot De', 19);
insert into hvs.product (id, name, wanted_amount) values (688, 'Chocolate - White', 28);
insert into hvs.product (id, name, wanted_amount) values (689, 'The Pop Shoppe Pinapple', 53);
insert into hvs.product (id, name, wanted_amount) values (690, 'Bread - Pain Au Liat X12', 34);
insert into hvs.product (id, name, wanted_amount) values (691, 'Lamb - Leg, Diced', 54);
insert into hvs.product (id, name, wanted_amount) values (692, 'General Purpose Trigger', 27);
insert into hvs.product (id, name, wanted_amount) values (693, 'Radish - Black, Winter, Organic', 73);
insert into hvs.product (id, name, wanted_amount) values (694, 'Hot Choc Vending', 58);
insert into hvs.product (id, name, wanted_amount) values (695, 'Bagels Poppyseed', 78);
insert into hvs.product (id, name, wanted_amount) values (696, 'Container - Foam Dixie 12 Oz', 71);
insert into hvs.product (id, name, wanted_amount) values (697, 'Chinese Foods - Chicken', 50);
insert into hvs.product (id, name, wanted_amount) values (698, 'Carbonated Water - Cherry', 100);
insert into hvs.product (id, name, wanted_amount) values (699, 'Juice - Pineapple, 341 Ml', 97);
insert into hvs.product (id, name, wanted_amount) values (700, 'Eggplant - Regular', 73);
insert into hvs.product (id, name, wanted_amount) values (701, 'Muskox - French Rack', 2);
insert into hvs.product (id, name, wanted_amount) values (702, 'Lettuce - Iceberg', 96);
insert into hvs.product (id, name, wanted_amount) values (703, 'Tomatoes - Vine Ripe, Yellow', 33);
insert into hvs.product (id, name, wanted_amount) values (704, 'Mix - Cocktail Strawberry Daiquiri', 34);
insert into hvs.product (id, name, wanted_amount) values (705, 'Beans - Kidney, Canned', 85);
insert into hvs.product (id, name, wanted_amount) values (706, 'Tomatoes - Orange', 71);
insert into hvs.product (id, name, wanted_amount) values (707, 'Raspberries - Frozen', 20);
insert into hvs.product (id, name, wanted_amount) values (708, 'Arctic Char - Fillets', 76);
insert into hvs.product (id, name, wanted_amount) values (709, 'Lemonade - Kiwi, 591 Ml', 43);
insert into hvs.product (id, name, wanted_amount) values (710, 'Wine - Valpolicella Masi', 21);
insert into hvs.product (id, name, wanted_amount) values (711, 'Munchies Honey Sweet Trail Mix', 94);
insert into hvs.product (id, name, wanted_amount) values (712, 'Water, Tap', 80);
insert into hvs.product (id, name, wanted_amount) values (713, 'Artichoke - Fresh', 33);
insert into hvs.product (id, name, wanted_amount) values (714, 'Muffin Hinge - 211n', 1);
insert into hvs.product (id, name, wanted_amount) values (715, 'Cassis', 8);
insert into hvs.product (id, name, wanted_amount) values (716, 'Bread - Sour Sticks With Onion', 16);
insert into hvs.product (id, name, wanted_amount) values (717, 'Squid Ink', 11);
insert into hvs.product (id, name, wanted_amount) values (718, 'Tomato - Green', 61);
insert into hvs.product (id, name, wanted_amount) values (719, 'Extract - Vanilla,artificial', 56);
insert into hvs.product (id, name, wanted_amount) values (720, 'Muffin - Mix - Mango Sour Cherry', 30);
insert into hvs.product (id, name, wanted_amount) values (721, 'Cake - Cheese Cake 9 Inch', 65);
insert into hvs.product (id, name, wanted_amount) values (722, 'Pastry - Baked Cinnamon Stick', 52);
insert into hvs.product (id, name, wanted_amount) values (723, 'Roe - Lump Fish, Red', 13);
insert into hvs.product (id, name, wanted_amount) values (724, 'Veal - Leg', 75);
insert into hvs.product (id, name, wanted_amount) values (725, 'Milk - Condensed', 86);
insert into hvs.product (id, name, wanted_amount) values (726, 'Beer - Steamwhistle', 30);
insert into hvs.product (id, name, wanted_amount) values (727, 'Sandwich Wrap', 94);
insert into hvs.product (id, name, wanted_amount) values (728, 'Butter - Unsalted', 80);
insert into hvs.product (id, name, wanted_amount) values (729, 'Bread - Roll, Soft White Round', 36);
insert into hvs.product (id, name, wanted_amount) values (730, 'Wine - Winzer Krems Gruner', 62);
insert into hvs.product (id, name, wanted_amount) values (731, 'Raisin - Golden', 87);
insert into hvs.product (id, name, wanted_amount) values (732, 'Chicken - Breast, 5 - 7 Oz', 80);
insert into hvs.product (id, name, wanted_amount) values (733, 'Cheese - Brick With Onion', 33);
insert into hvs.product (id, name, wanted_amount) values (734, 'Allspice - Jamaican', 7);
insert into hvs.product (id, name, wanted_amount) values (735, 'Beef Flat Iron Steak', 23);
insert into hvs.product (id, name, wanted_amount) values (736, 'Jagermeister', 100);
insert into hvs.product (id, name, wanted_amount) values (737, 'Cheese - Le Cheve Noir', 84);
insert into hvs.product (id, name, wanted_amount) values (738, 'Doilies - 5, Paper', 71);
insert into hvs.product (id, name, wanted_amount) values (739, 'Hersey Shakes', 22);
insert into hvs.product (id, name, wanted_amount) values (740, 'Cheese - St. Andre', 74);
insert into hvs.product (id, name, wanted_amount) values (741, 'Pants Custom Dry Clean', 14);
insert into hvs.product (id, name, wanted_amount) values (742, 'Canadian Emmenthal', 44);
insert into hvs.product (id, name, wanted_amount) values (743, 'Milk - Buttermilk', 39);
insert into hvs.product (id, name, wanted_amount) values (744, 'Oil - Truffle, White', 42);
insert into hvs.product (id, name, wanted_amount) values (745, 'Coriander - Seed', 48);
insert into hvs.product (id, name, wanted_amount) values (746, 'Bread - Focaccia Quarter', 47);
insert into hvs.product (id, name, wanted_amount) values (747, 'Muffin - Mix - Bran And Maple 15l', 91);
insert into hvs.product (id, name, wanted_amount) values (748, 'Gelatine Leaves - Envelopes', 87);
insert into hvs.product (id, name, wanted_amount) values (749, 'Sauce - White, Mix', 91);
insert into hvs.product (id, name, wanted_amount) values (750, 'Lettuce - Green Leaf', 8);
insert into hvs.product (id, name, wanted_amount) values (751, 'Pail - 4l White, With Handle', 20);
insert into hvs.product (id, name, wanted_amount) values (752, 'Sauce - Hp', 91);
insert into hvs.product (id, name, wanted_amount) values (753, '7up Diet, 355 Ml', 79);
insert into hvs.product (id, name, wanted_amount) values (754, 'Salmon - Whole, 4 - 6 Pounds', 6);
insert into hvs.product (id, name, wanted_amount) values (755, 'Wine - Red, Mouton Cadet', 17);
insert into hvs.product (id, name, wanted_amount) values (756, 'Red Currants', 14);
insert into hvs.product (id, name, wanted_amount) values (757, 'Beans - Fine', 45);
insert into hvs.product (id, name, wanted_amount) values (758, 'Barley - Pearl', 58);
insert into hvs.product (id, name, wanted_amount) values (759, 'Rice - 7 Grain Blend', 37);
insert into hvs.product (id, name, wanted_amount) values (760, 'Chinese Foods - Thick Noodles', 9);
insert into hvs.product (id, name, wanted_amount) values (761, 'Soup - Campbells Chili Veg', 81);
insert into hvs.product (id, name, wanted_amount) values (762, 'Beer - Fruli', 21);
insert into hvs.product (id, name, wanted_amount) values (763, 'Muffin - Zero Transfat', 9);
insert into hvs.product (id, name, wanted_amount) values (764, 'V8 Pet', 20);
insert into hvs.product (id, name, wanted_amount) values (765, 'Lettuce - Radicchio', 69);
insert into hvs.product (id, name, wanted_amount) values (766, 'Lumpfish Black', 70);
insert into hvs.product (id, name, wanted_amount) values (767, 'Yeast Dry - Fermipan', 18);
insert into hvs.product (id, name, wanted_amount) values (768, 'Chicken - Wings, Tip Off', 69);
insert into hvs.product (id, name, wanted_amount) values (769, 'Fish - Soup Base, Bouillon', 64);
insert into hvs.product (id, name, wanted_amount) values (770, 'Tumeric', 34);
insert into hvs.product (id, name, wanted_amount) values (771, 'Buffalo - Tenderloin', 11);
insert into hvs.product (id, name, wanted_amount) values (772, 'Beer - Fruli', 85);
insert into hvs.product (id, name, wanted_amount) values (773, 'Pepper - Chilli Seeds Mild', 61);
insert into hvs.product (id, name, wanted_amount) values (774, 'Cheese - St. Paulin', 69);
insert into hvs.product (id, name, wanted_amount) values (775, 'Placemat - Scallop, White', 15);
insert into hvs.product (id, name, wanted_amount) values (776, 'Fish - Halibut, Cold Smoked', 77);
insert into hvs.product (id, name, wanted_amount) values (777, 'Wine - White, Mosel Gold', 66);
insert into hvs.product (id, name, wanted_amount) values (778, 'Coffee - Decafenated', 73);
insert into hvs.product (id, name, wanted_amount) values (779, 'Yams', 38);
insert into hvs.product (id, name, wanted_amount) values (780, 'Pork - Smoked Kassler', 31);
insert into hvs.product (id, name, wanted_amount) values (781, 'Turnip - White', 2);
insert into hvs.product (id, name, wanted_amount) values (782, 'Cookie - Oreo 100x2', 45);
insert into hvs.product (id, name, wanted_amount) values (783, 'Mushrooms - Honey', 6);
insert into hvs.product (id, name, wanted_amount) values (784, 'Tart Shells - Savory, 3', 36);
insert into hvs.product (id, name, wanted_amount) values (785, 'Eel Fresh', 96);
insert into hvs.product (id, name, wanted_amount) values (786, 'Beer - Molson Excel', 37);
insert into hvs.product (id, name, wanted_amount) values (787, 'Cheese - Cheddar, Medium', 25);
insert into hvs.product (id, name, wanted_amount) values (788, 'Port - 74 Brights', 19);
insert into hvs.product (id, name, wanted_amount) values (789, 'Cheese - Victor Et Berthold', 23);
insert into hvs.product (id, name, wanted_amount) values (790, 'Coffee - Ristretto Coffee Capsule', 21);
insert into hvs.product (id, name, wanted_amount) values (791, 'Port - 74 Brights', 52);
insert into hvs.product (id, name, wanted_amount) values (792, 'Tabasco Sauce, 2 Oz', 45);
insert into hvs.product (id, name, wanted_amount) values (793, 'Bread - Calabrese Baguette', 3);
insert into hvs.product (id, name, wanted_amount) values (794, 'Pork - Ham Hocks - Smoked', 78);
insert into hvs.product (id, name, wanted_amount) values (795, 'Table Cloth - 53x69 Colour', 55);
insert into hvs.product (id, name, wanted_amount) values (796, 'Wine - Wyndham Estate Bin 777', 73);
insert into hvs.product (id, name, wanted_amount) values (797, 'Cheese - Comtomme', 63);
insert into hvs.product (id, name, wanted_amount) values (798, 'Kellogs Raisan Bran Bars', 31);
insert into hvs.product (id, name, wanted_amount) values (799, 'Sugar - Palm', 34);
insert into hvs.product (id, name, wanted_amount) values (800, 'Leeks - Baby, White', 75);
insert into hvs.product (id, name, wanted_amount) values (801, 'Artichoke - Bottom, Canned', 46);
insert into hvs.product (id, name, wanted_amount) values (802, 'Wine - Red, Gamay Noir', 46);
insert into hvs.product (id, name, wanted_amount) values (803, 'Crab - Back Fin Meat, Canned', 97);
insert into hvs.product (id, name, wanted_amount) values (804, 'Beets - Mini Golden', 96);
insert into hvs.product (id, name, wanted_amount) values (805, 'Soap - Pine Sol Floor Cleaner', 1);
insert into hvs.product (id, name, wanted_amount) values (806, 'Sugar Thermometer', 70);
insert into hvs.product (id, name, wanted_amount) values (807, 'Gherkin - Sour', 51);
insert into hvs.product (id, name, wanted_amount) values (808, 'Steel Wool S.o.s', 72);
insert into hvs.product (id, name, wanted_amount) values (809, 'Sea Bass - Fillets', 52);
insert into hvs.product (id, name, wanted_amount) values (810, 'Coconut - Whole', 55);
insert into hvs.product (id, name, wanted_amount) values (811, 'Flour - Bran, Red', 19);
insert into hvs.product (id, name, wanted_amount) values (812, 'Eel Fresh', 7);
insert into hvs.product (id, name, wanted_amount) values (813, 'Soup - Campbells Chicken', 14);
insert into hvs.product (id, name, wanted_amount) values (814, 'Barley - Pearl', 73);
insert into hvs.product (id, name, wanted_amount) values (815, 'Cauliflower', 89);
insert into hvs.product (id, name, wanted_amount) values (816, 'Wine - Fat Bastard Merlot', 63);
insert into hvs.product (id, name, wanted_amount) values (817, 'Potatoes - Pei 10 Oz', 34);
insert into hvs.product (id, name, wanted_amount) values (818, 'Pears - Anjou', 36);
insert into hvs.product (id, name, wanted_amount) values (819, 'Sauerkraut', 38);
insert into hvs.product (id, name, wanted_amount) values (820, 'Mushroom - Enoki, Fresh', 43);
insert into hvs.product (id, name, wanted_amount) values (821, 'Cheese - Gouda Smoked', 54);
insert into hvs.product (id, name, wanted_amount) values (822, 'Turnip - White', 46);
insert into hvs.product (id, name, wanted_amount) values (823, 'Wine - Magnotta, Merlot Sr Vqa', 66);
insert into hvs.product (id, name, wanted_amount) values (824, 'Sauce - Hp', 10);
insert into hvs.product (id, name, wanted_amount) values (825, 'Table Cloth 90x90 Colour', 8);
insert into hvs.product (id, name, wanted_amount) values (826, 'Pasta - Fusili, Dry', 76);
insert into hvs.product (id, name, wanted_amount) values (827, 'Crab - Claws, 26 - 30', 76);
insert into hvs.product (id, name, wanted_amount) values (828, 'Soup - Campbells Pasta Fagioli', 47);
insert into hvs.product (id, name, wanted_amount) values (829, 'Wine - Pinot Grigio Collavini', 38);
insert into hvs.product (id, name, wanted_amount) values (830, 'Island Oasis - Magarita Mix', 54);
insert into hvs.product (id, name, wanted_amount) values (831, 'Wine - Delicato Merlot', 66);
insert into hvs.product (id, name, wanted_amount) values (832, 'Tahini Paste', 20);
insert into hvs.product (id, name, wanted_amount) values (833, 'Cornstarch', 42);
insert into hvs.product (id, name, wanted_amount) values (834, 'Cheese - Sheep Milk', 57);
insert into hvs.product (id, name, wanted_amount) values (835, 'Sauce - Cranberry', 24);
insert into hvs.product (id, name, wanted_amount) values (836, 'Oranges', 30);
insert into hvs.product (id, name, wanted_amount) values (837, 'Longos - Lasagna Beef', 47);
insert into hvs.product (id, name, wanted_amount) values (838, 'Leeks - Large', 57);
insert into hvs.product (id, name, wanted_amount) values (839, 'Bread - Frozen Basket Variety', 24);
insert into hvs.product (id, name, wanted_amount) values (840, 'Dragon Fruit', 52);
insert into hvs.product (id, name, wanted_amount) values (841, 'Chinese Foods - Thick Noodles', 69);
insert into hvs.product (id, name, wanted_amount) values (842, 'Basil - Thai', 76);
insert into hvs.product (id, name, wanted_amount) values (843, 'Cheese - Cheddar, Mild', 68);
insert into hvs.product (id, name, wanted_amount) values (844, 'Eggwhite Frozen', 48);
insert into hvs.product (id, name, wanted_amount) values (845, 'Crab Meat Claw Pasteurise', 87);
insert into hvs.product (id, name, wanted_amount) values (846, 'Alize Gold Passion', 44);
insert into hvs.product (id, name, wanted_amount) values (847, 'Skewers - Bamboo', 18);
insert into hvs.product (id, name, wanted_amount) values (848, 'Pork - European Side Bacon', 6);
insert into hvs.product (id, name, wanted_amount) values (849, 'Cheese - Le Cheve Noir', 68);
insert into hvs.product (id, name, wanted_amount) values (850, 'Onions - Cippolini', 51);
insert into hvs.product (id, name, wanted_amount) values (851, 'Truffle Cups - Brown', 93);
insert into hvs.product (id, name, wanted_amount) values (852, 'Daves Island Stinger', 67);
insert into hvs.product (id, name, wanted_amount) values (853, 'Rosemary - Dry', 97);
insert into hvs.product (id, name, wanted_amount) values (854, 'Cake - Dulce De Leche', 9);
insert into hvs.product (id, name, wanted_amount) values (855, 'Pasta - Ravioli', 28);
insert into hvs.product (id, name, wanted_amount) values (856, 'Veal - Sweetbread', 87);
insert into hvs.product (id, name, wanted_amount) values (857, 'Nutmeg - Ground', 49);
insert into hvs.product (id, name, wanted_amount) values (858, 'Rootbeer', 95);
insert into hvs.product (id, name, wanted_amount) values (859, 'Soup - Campbells Chili Veg', 91);
insert into hvs.product (id, name, wanted_amount) values (860, 'Mussels - Cultivated', 100);
insert into hvs.product (id, name, wanted_amount) values (861, 'Beer - Paulaner Hefeweisse', 43);
insert into hvs.product (id, name, wanted_amount) values (862, 'Oats Large Flake', 10);
insert into hvs.product (id, name, wanted_amount) values (863, 'Pork - Bacon Cooked Slcd', 5);
insert into hvs.product (id, name, wanted_amount) values (864, 'Dates', 40);
insert into hvs.product (id, name, wanted_amount) values (865, 'Pork - Tenderloin, Frozen', 87);
insert into hvs.product (id, name, wanted_amount) values (866, 'Parsley - Fresh', 37);
insert into hvs.product (id, name, wanted_amount) values (867, 'Parsley Italian - Fresh', 25);
insert into hvs.product (id, name, wanted_amount) values (868, 'Poppy Seed', 56);
insert into hvs.product (id, name, wanted_amount) values (869, 'Cheese - Mix', 97);
insert into hvs.product (id, name, wanted_amount) values (870, 'Lotus Root', 45);
insert into hvs.product (id, name, wanted_amount) values (871, 'Tofu - Soft', 44);
insert into hvs.product (id, name, wanted_amount) values (872, 'Mayonnaise', 98);
insert into hvs.product (id, name, wanted_amount) values (873, 'Beer - True North Lager', 72);
insert into hvs.product (id, name, wanted_amount) values (874, 'Rye Special Old', 67);
insert into hvs.product (id, name, wanted_amount) values (875, 'Silicone Paper 16.5x24', 4);
insert into hvs.product (id, name, wanted_amount) values (876, 'Bag - Regular Kraft 20 Lb', 95);
insert into hvs.product (id, name, wanted_amount) values (877, 'Beef - Tender Tips', 41);
insert into hvs.product (id, name, wanted_amount) values (878, 'Sprouts - Corn', 2);
insert into hvs.product (id, name, wanted_amount) values (879, 'Yogurt - Strawberry, 175 Gr', 19);
insert into hvs.product (id, name, wanted_amount) values (880, 'Chicken - White Meat With Tender', 71);
insert into hvs.product (id, name, wanted_amount) values (881, 'Roe - Lump Fish, Black', 6);
insert into hvs.product (id, name, wanted_amount) values (882, 'Bread - Granary Small Pull', 12);
insert into hvs.product (id, name, wanted_amount) values (883, 'Wine - Peller Estates Late', 33);
insert into hvs.product (id, name, wanted_amount) values (884, 'Peas - Frozen', 55);
insert into hvs.product (id, name, wanted_amount) values (885, 'Beef - Prime Rib Aaa', 13);
insert into hvs.product (id, name, wanted_amount) values (886, 'Cocoa Powder - Natural', 74);
insert into hvs.product (id, name, wanted_amount) values (887, 'Caviar - Salmon', 46);
insert into hvs.product (id, name, wanted_amount) values (888, 'Cheese - Swiss Sliced', 12);
insert into hvs.product (id, name, wanted_amount) values (889, 'Paper - Brown Paper Mini Cups', 78);
insert into hvs.product (id, name, wanted_amount) values (890, 'Bread - Roll, Calabrese', 30);
insert into hvs.product (id, name, wanted_amount) values (891, 'Nut - Almond, Blanched, Ground', 10);
insert into hvs.product (id, name, wanted_amount) values (892, 'Tea - Herbal Orange Spice', 50);
insert into hvs.product (id, name, wanted_amount) values (893, 'Oil - Hazelnut', 41);
insert into hvs.product (id, name, wanted_amount) values (894, 'Pork - Bacon, Sliced', 87);
insert into hvs.product (id, name, wanted_amount) values (895, 'Soup - Beef Conomme, Dry', 96);
insert into hvs.product (id, name, wanted_amount) values (896, 'Rum - Mount Gay Eclipes', 100);
insert into hvs.product (id, name, wanted_amount) values (897, 'Cookies - Englishbay Oatmeal', 84);
insert into hvs.product (id, name, wanted_amount) values (898, 'Cheese - St. Paulin', 18);
insert into hvs.product (id, name, wanted_amount) values (899, 'Banana - Green', 28);
insert into hvs.product (id, name, wanted_amount) values (900, 'Chocolate Bar - Oh Henry', 31);
insert into hvs.product (id, name, wanted_amount) values (901, 'Salt - Table', 83);
insert into hvs.product (id, name, wanted_amount) values (902, 'V8 Splash Strawberry Kiwi', 4);
insert into hvs.product (id, name, wanted_amount) values (903, 'Asparagus - Green, Fresh', 75);
insert into hvs.product (id, name, wanted_amount) values (904, 'V8 - Vegetable Cocktail', 58);
insert into hvs.product (id, name, wanted_amount) values (905, 'Sterno - Chafing Dish Fuel', 89);
insert into hvs.product (id, name, wanted_amount) values (906, 'Soup Campbells - Italian Wedding', 49);
insert into hvs.product (id, name, wanted_amount) values (907, 'Wine - Vouvray Cuvee Domaine', 71);
insert into hvs.product (id, name, wanted_amount) values (908, 'Nut - Pine Nuts, Whole', 45);
insert into hvs.product (id, name, wanted_amount) values (909, 'Chicken - Leg, Boneless', 59);
insert into hvs.product (id, name, wanted_amount) values (910, 'Pike - Frozen Fillet', 41);
insert into hvs.product (id, name, wanted_amount) values (911, 'Ice Cream Bar - Hageen Daz To', 79);
insert into hvs.product (id, name, wanted_amount) values (912, 'Sugar - Invert', 79);
insert into hvs.product (id, name, wanted_amount) values (913, 'Shrimp - 16/20, Peeled Deviened', 83);
insert into hvs.product (id, name, wanted_amount) values (914, 'Garlic Powder', 98);
insert into hvs.product (id, name, wanted_amount) values (915, 'Maintenance Removal Charge', 40);
insert into hvs.product (id, name, wanted_amount) values (916, 'Dried Peach', 62);
insert into hvs.product (id, name, wanted_amount) values (917, 'Sausage - Meat', 45);
insert into hvs.product (id, name, wanted_amount) values (918, 'Soup - French Onion', 82);
insert into hvs.product (id, name, wanted_amount) values (919, 'Longos - Chicken Caeser Salad', 12);
insert into hvs.product (id, name, wanted_amount) values (920, 'Napkin - Beverage 1 Ply', 71);
insert into hvs.product (id, name, wanted_amount) values (921, 'Passion Fruit', 44);
insert into hvs.product (id, name, wanted_amount) values (922, 'Wine - Red, Concha Y Toro', 96);
insert into hvs.product (id, name, wanted_amount) values (923, 'Nacho Chips', 48);
insert into hvs.product (id, name, wanted_amount) values (924, 'Ice Cream - Super Sandwich', 100);
insert into hvs.product (id, name, wanted_amount) values (925, 'Quail - Jumbo Boneless', 49);
insert into hvs.product (id, name, wanted_amount) values (926, 'Beer - Upper Canada Lager', 100);
insert into hvs.product (id, name, wanted_amount) values (927, 'Glove - Cutting', 97);
insert into hvs.product (id, name, wanted_amount) values (928, 'Horseradish Root', 49);
insert into hvs.product (id, name, wanted_amount) values (929, 'Fish - Bones', 26);
insert into hvs.product (id, name, wanted_amount) values (930, 'Sprouts - Onion', 81);
insert into hvs.product (id, name, wanted_amount) values (931, 'Nantucket - Orange Mango Cktl', 42);
insert into hvs.product (id, name, wanted_amount) values (932, 'Sour Puss Sour Apple', 25);
insert into hvs.product (id, name, wanted_amount) values (933, 'Sterno - Chafing Dish Fuel', 64);
insert into hvs.product (id, name, wanted_amount) values (934, 'Chip - Potato Dill Pickle', 4);
insert into hvs.product (id, name, wanted_amount) values (935, 'Wine - Port Late Bottled Vintage', 17);
insert into hvs.product (id, name, wanted_amount) values (936, 'Cumin - Ground', 40);
insert into hvs.product (id, name, wanted_amount) values (937, 'Vodka - Moskovskaya', 18);
insert into hvs.product (id, name, wanted_amount) values (938, 'Sage Derby', 26);
insert into hvs.product (id, name, wanted_amount) values (939, 'Extract - Lemon', 29);
insert into hvs.product (id, name, wanted_amount) values (940, 'Beef - Cow Feet Split', 91);
insert into hvs.product (id, name, wanted_amount) values (941, 'Yogurt - French Vanilla', 7);
insert into hvs.product (id, name, wanted_amount) values (942, 'Mackerel Whole Fresh', 3);
insert into hvs.product (id, name, wanted_amount) values (943, 'Smoked Paprika', 43);
insert into hvs.product (id, name, wanted_amount) values (944, 'Rum - Light, Captain Morgan', 22);
insert into hvs.product (id, name, wanted_amount) values (945, 'Tuna - Bluefin', 22);
insert into hvs.product (id, name, wanted_amount) values (946, 'Bread - Sour Batard', 88);
insert into hvs.product (id, name, wanted_amount) values (947, 'White Baguette', 67);
insert into hvs.product (id, name, wanted_amount) values (948, 'Spinach - Spinach Leaf', 99);
insert into hvs.product (id, name, wanted_amount) values (949, 'Chips - Doritos', 70);
insert into hvs.product (id, name, wanted_amount) values (950, 'Kahlua', 54);
insert into hvs.product (id, name, wanted_amount) values (951, 'Muffin Mix - Morning Glory', 13);
insert into hvs.product (id, name, wanted_amount) values (952, 'Muffin Puck Ww Carrot', 72);
insert into hvs.product (id, name, wanted_amount) values (953, 'Fish - Base, Bouillion', 52);
insert into hvs.product (id, name, wanted_amount) values (954, 'Chocolate - Semi Sweet, Calets', 23);
insert into hvs.product (id, name, wanted_amount) values (955, 'Wine - Saint - Bris 2002, Sauv', 15);
insert into hvs.product (id, name, wanted_amount) values (956, 'Butter - Pod', 19);
insert into hvs.product (id, name, wanted_amount) values (957, 'Pork Ham Prager', 28);
insert into hvs.product (id, name, wanted_amount) values (958, 'Lettuce - Frisee', 49);
insert into hvs.product (id, name, wanted_amount) values (959, 'Salt - Rock, Course', 49);
insert into hvs.product (id, name, wanted_amount) values (960, 'Soup - Boston Clam Chowder', 39);
insert into hvs.product (id, name, wanted_amount) values (961, 'Coriander - Ground', 50);
insert into hvs.product (id, name, wanted_amount) values (962, 'Appetiser - Bought', 14);
insert into hvs.product (id, name, wanted_amount) values (963, 'Bread - Triangle White', 63);
insert into hvs.product (id, name, wanted_amount) values (964, 'Lettuce - Lambs Mash', 43);
insert into hvs.product (id, name, wanted_amount) values (965, 'Chicken - White Meat, No Tender', 71);
insert into hvs.product (id, name, wanted_amount) values (966, 'Apricots Fresh', 61);
insert into hvs.product (id, name, wanted_amount) values (967, 'Marsala - Sperone, Fine, D.o.c.', 16);
insert into hvs.product (id, name, wanted_amount) values (968, 'Sprouts - Alfalfa', 82);
insert into hvs.product (id, name, wanted_amount) values (969, 'Bread - English Muffin', 61);
insert into hvs.product (id, name, wanted_amount) values (970, 'Bread - Pumpernickel', 66);
insert into hvs.product (id, name, wanted_amount) values (971, 'Absolut Citron', 13);
insert into hvs.product (id, name, wanted_amount) values (972, 'Mushroom - Shitake, Fresh', 12);
insert into hvs.product (id, name, wanted_amount) values (973, 'Sauce - White, Mix', 40);
insert into hvs.product (id, name, wanted_amount) values (974, 'Cinnamon - Stick', 83);
insert into hvs.product (id, name, wanted_amount) values (975, 'Lettuce - Red Leaf', 46);
insert into hvs.product (id, name, wanted_amount) values (976, 'Versatainer Nc - 9388', 10);
insert into hvs.product (id, name, wanted_amount) values (977, 'Lettuce - Radicchio', 53);
insert into hvs.product (id, name, wanted_amount) values (978, 'Brandy Cherry - Mcguinness', 56);
insert into hvs.product (id, name, wanted_amount) values (979, 'Ice Cream - Life Savers', 30);
insert into hvs.product (id, name, wanted_amount) values (980, 'Doilies - 5, Paper', 3);
insert into hvs.product (id, name, wanted_amount) values (981, 'Flavouring - Rum', 31);
insert into hvs.product (id, name, wanted_amount) values (982, 'Syrup - Monin - Passion Fruit', 80);
insert into hvs.product (id, name, wanted_amount) values (983, 'Wine - Rhine Riesling Wolf Blass', 72);
insert into hvs.product (id, name, wanted_amount) values (984, 'Salad Dressing', 41);
insert into hvs.product (id, name, wanted_amount) values (985, 'Eel Fresh', 77);
insert into hvs.product (id, name, wanted_amount) values (986, 'Squash - Pepper', 82);
insert into hvs.product (id, name, wanted_amount) values (987, 'Chef Hat 20cm', 53);
insert into hvs.product (id, name, wanted_amount) values (988, 'Apricots - Dried', 16);
insert into hvs.product (id, name, wanted_amount) values (989, 'Pork - Bacon, Sliced', 73);
insert into hvs.product (id, name, wanted_amount) values (990, 'Pie Shell - 9', 73);
insert into hvs.product (id, name, wanted_amount) values (991, 'Vinegar - Balsamic', 36);
insert into hvs.product (id, name, wanted_amount) values (992, 'Carbonated Water - Blackcherry', 57);
insert into hvs.product (id, name, wanted_amount) values (993, 'Snapple Raspberry Tea', 29);
insert into hvs.product (id, name, wanted_amount) values (994, 'Hold Up Tool Storage Rack', 82);
insert into hvs.product (id, name, wanted_amount) values (995, 'Papayas', 1);
insert into hvs.product (id, name, wanted_amount) values (996, 'Beef - Cooked, Corned', 33);
insert into hvs.product (id, name, wanted_amount) values (997, 'Stock - Veal, White', 80);
insert into hvs.product (id, name, wanted_amount) values (998, 'Tuna - Loin', 96);
insert into hvs.product (id, name, wanted_amount) values (999, 'Chicken - White Meat With Tender', 71);
insert into hvs.product (id, name, wanted_amount) values (1000, 'Honey - Comb', 76);
